<?php

if ( ! defined('_DEBUG_THROWABLER_WITH_CODE') ) define('_DEBUG_THROWABLER_WITH_CODE', 1 << 1);
if ( ! defined('_DEBUG_THROWABLER_WITHOUT_CODE') ) define('_DEBUG_THROWABLER_WITHOUT_CODE', 1 << 2);

if ( ! defined('_DEBUG_THROWABLER_WITH_INFO') ) define('_DEBUG_THROWABLER_WITH_INFO', 1 << 3);
if ( ! defined('_DEBUG_THROWABLER_WITHOUT_INFO') ) define('_DEBUG_THROWABLER_WITHOUT_INFO', 1 << 4);

if ( ! defined('_DEBUG_THROWABLER_WITH_TRACE') ) define('_DEBUG_THROWABLER_WITH_TRACE', 1 << 5);
if ( ! defined('_DEBUG_THROWABLER_WITHOUT_TRACE') ) define('_DEBUG_THROWABLER_WITHOUT_TRACE', 1 << 6);


if ( ! defined('_DEBUG_THROWABLER_INFO_WITH_FILE') ) define('_DEBUG_THROWABLER_INFO_WITH_FILE', 1 << 7);
if ( ! defined('_DEBUG_THROWABLER_INFO_WITHOUT_FILE') ) define('_DEBUG_THROWABLER_INFO_WITHOUT_FILE', 1 << 8);

if ( ! defined('_DEBUG_THROWABLER_INFO_WITH_OBJECT_CLASS') ) define('_DEBUG_THROWABLER_INFO_WITH_OBJECT_CLASS', 1 << 9);
if ( ! defined('_DEBUG_THROWABLER_INFO_WITHOUT_OBJECT_CLASS') ) define('_DEBUG_THROWABLER_INFO_WITHOUT_OBJECT_CLASS', 1 << 10);

if ( ! defined('_DEBUG_THROWABLER_INFO_WITH_OBJECT_ID') ) define('_DEBUG_THROWABLER_INFO_WITH_OBJECT_ID', 1 << 11);
if ( ! defined('_DEBUG_THROWABLER_INFO_WITHOUT_OBJECT_ID') ) define('_DEBUG_THROWABLER_INFO_WITHOUT_OBJECT_ID', 1 << 12);
