<?php

if (! defined('_DEBUG_THROWABLE_WITH_CODE')) define('_DEBUG_THROWABLE_WITH_CODE', 1 << 1);
if (! defined('_DEBUG_THROWABLE_WITHOUT_CODE')) define('_DEBUG_THROWABLE_WITHOUT_CODE', 1 << 2);

if (! defined('_DEBUG_THROWABLE_WITH_FILE')) define('_DEBUG_THROWABLE_WITH_FILE', 1 << 3);
if (! defined('_DEBUG_THROWABLE_WITHOUT_FILE')) define('_DEBUG_THROWABLE_WITHOUT_FILE', 1 << 4);

if (! defined('_DEBUG_THROWABLE_WITH_OBJECT_CLASS')) define('_DEBUG_THROWABLE_WITH_OBJECT_CLASS', 1 << 5);
if (! defined('_DEBUG_THROWABLE_WITHOUT_OBJECT_CLASS')) define('_DEBUG_THROWABLE_WITHOUT_OBJECT_CLASS', 1 << 6);

if (! defined('_DEBUG_THROWABLE_WITH_OBJECT_ID')) define('_DEBUG_THROWABLE_WITH_OBJECT_ID', 1 << 7);
if (! defined('_DEBUG_THROWABLE_WITHOUT_OBJECT_ID')) define('_DEBUG_THROWABLE_WITHOUT_OBJECT_ID', 1 << 8);

if (! defined('_DEBUG_THROWABLE_WITH_PARENTS')) define('_DEBUG_THROWABLE_WITH_PARENTS', 1 << 9);
if (! defined('_DEBUG_THROWABLE_WITHOUT_PARENTS')) define('_DEBUG_THROWABLE_WITHOUT_PARENTS', 1 << 10);
