<?php

/**
 * This class is autogenerated.
 *
 * @noinspection PhpComposerExtensionStubsInspection
 */

namespace Gzhegow\Lib\Modules\Type\Traits;

use Gzhegow\Lib\Lib;

trait BoolTrait
{
	public function php_array($value): bool
	{
		return Lib::arr()->type_php_array(null, $value)->isOk();
	}


	public function php_array_empty($value): bool
	{
		return Lib::arr()->type_php_array_empty(null, $value)->isOk();
	}


	public function php_array_not_empty($value): bool
	{
		return Lib::arr()->type_php_array_not_empty(null, $value)->isOk();
	}


	public function not_php_array($value): bool
	{
		return Lib::arr()->type_not_php_array(null, $value)->isOk();
	}


	public function array($value, bool $isPlain = null): bool
	{
		return Lib::arr()->type_array(null, $value, $isPlain)->isOk();
	}


	public function array_recursive($value, int $maxDepth = null): bool
	{
		return Lib::arr()->type_array_recursive(null, $value, $maxDepth)->isOk();
	}


	public function array_empty($value): bool
	{
		return Lib::arr()->type_array_empty(null, $value)->isOk();
	}


	public function array_not_empty($value): bool
	{
		return Lib::arr()->type_array_not_empty(null, $value)->isOk();
	}


	public function not_array($value): bool
	{
		return Lib::arr()->type_not_array(null, $value)->isOk();
	}


	/**
	 * @param callable $fnSortKeysCmp
	 */
	public function array_sorted($value, bool $isPlain = null, $fnSortKeysCmp = null): bool
	{
		return Lib::arr()->type_array_sorted(null, $value, $isPlain, $fnSortKeysCmp)->isOk();
	}


	/**
	 * @param callable $fnSortKeysCmp
	 */
	public function array_sorted_recursive($value, int $maxDepth = null, $fnSortKeysCmp = null): bool
	{
		return Lib::arr()->type_array_sorted_recursive(null, $value, $maxDepth, $fnSortKeysCmp)->isOk();
	}


	public function array_of_type($value, string $type): bool
	{
		return Lib::arr()->type_array_of_type(null, $value, $type)->isOk();
	}


	public function array_of_resource_type($value, string $resourceType): bool
	{
		return Lib::arr()->type_array_of_resource_type(null, $value, $resourceType)->isOk();
	}


	/**
	 * @template T
	 *
	 * @param class-string<T> $className
	 */
	public function array_of_a($value, string $className): bool
	{
		return Lib::arr()->type_array_of_a(null, $value, $className)->isOk();
	}


	/**
	 * @template T
	 *
	 * @param class-string<T> $className
	 */
	public function array_of_class($value, string $className): bool
	{
		return Lib::arr()->type_array_of_class(null, $value, $className)->isOk();
	}


	/**
	 * @template T
	 *
	 * @param class-string<T> $className
	 */
	public function array_of_subclass($value, string $className): bool
	{
		return Lib::arr()->type_array_of_subclass(null, $value, $className)->isOk();
	}


	/**
	 * @param callable $fn
	 *
	 *
	 * @noinspection PhpDocSignatureIsNotCompleteInspection
	 */
	public function array_of_callback($value, callable $fn, array $fnArgs = []): bool
	{
		return Lib::arr()->type_array_of_callback(null, $value, $fn, $fnArgs)->isOk();
	}


	public function array_key($key): bool
	{
		return Lib::arr()->type_array_key(null, $key)->isOk();
	}


	public function array_key_exists(array $array, $key): bool
	{
		return Lib::arr()->type_array_key_exists(null, $array, $key)->isOk();
	}


	public function value_in_array(array $array, $value, bool $isStrict = null): bool
	{
		return Lib::arr()->type_value_in_array(null, $array, $value, $isStrict)->isOk();
	}


	public function value_in_array_key(array $array, $value, bool $isStrict = null): bool
	{
		return Lib::arr()->type_value_in_array_key(null, $array, $value, $isStrict)->isOk();
	}


	public function value_in_array_pos(array $array, $value, bool $isStrict = null): bool
	{
		return Lib::arr()->type_value_in_array_pos(null, $array, $value, $isStrict)->isOk();
	}


	public function array_keys_exists(array $array, $keys): bool
	{
		return Lib::arr()->type_array_keys_exists(null, $array, $keys)->isOk();
	}


	public function array_keys_not_exists(array $array, $keys): bool
	{
		return Lib::arr()->type_array_keys_not_exists(null, $array, $keys)->isOk();
	}


	public function values_in_array(array $array, $values, bool $strict = null): bool
	{
		return Lib::arr()->type_values_in_array(null, $array, $values, $strict)->isOk();
	}


	public function values_not_in_array(array $array, $values, bool $strict = null): bool
	{
		return Lib::arr()->type_values_not_in_array(null, $array, $values, $strict)->isOk();
	}


	public function list($value, bool $isPlain = null): bool
	{
		return Lib::arr()->type_list(null, $value, $isPlain)->isOk();
	}


	public function list_recursive($value, int $maxDepth = null): bool
	{
		return Lib::arr()->type_list_recursive(null, $value, $maxDepth)->isOk();
	}


	public function list_sorted($value, bool $isPlain = null): bool
	{
		return Lib::arr()->type_list_sorted(null, $value, $isPlain)->isOk();
	}


	public function list_sorted_recursive($value, int $maxDepth = null): bool
	{
		return Lib::arr()->type_list_sorted_recursive(null, $value, $maxDepth)->isOk();
	}


	public function dict($value, bool $isPlain = null): bool
	{
		return Lib::arr()->type_dict(null, $value, $isPlain)->isOk();
	}


	public function dict_recursive($value, int $maxDepth = null): bool
	{
		return Lib::arr()->type_dict_recursive(null, $value, $maxDepth)->isOk();
	}


	/**
	 * @param callable $fnSortKeysCmp
	 */
	public function dict_sorted($value, bool $isPlain = null, $fnSortKeysCmp = null): bool
	{
		return Lib::arr()->type_dict_sorted(null, $value, $isPlain, $fnSortKeysCmp)->isOk();
	}


	/**
	 * @param callable $fnSortKeysCmp
	 */
	public function dict_sorted_recursive($value, int $maxDepth = null, $fnSortKeysCmp = null): bool
	{
		return Lib::arr()->type_dict_sorted_recursive(null, $value, $maxDepth, $fnSortKeysCmp)->isOk();
	}


	public function table($value, int $isListOrDict = null, bool $isChildrenPlain = null): bool
	{
		return Lib::arr()->type_table(null, $value, $isListOrDict, $isChildrenPlain)->isOk();
	}


	/**
	 * @param callable $fnSortKeysCmp
	 */
	public function table_sorted(
		$value,
		int $isListOrDict = null,
		bool $isChildrenPlain = null,
		$fnSortKeysCmp = null
	): bool {
		return Lib::arr()->type_table_sorted(null, $value, $isListOrDict, $isChildrenPlain, $fnSortKeysCmp)->isOk();
	}


	public function matrix($value, bool $isChildrenPlain = null): bool
	{
		return Lib::arr()->type_matrix(null, $value, $isChildrenPlain)->isOk();
	}


	public function matrix_recursive($value, int $maxDepth = null): bool
	{
		return Lib::arr()->type_matrix_recursive(null, $value, $maxDepth)->isOk();
	}


	public function arrpath($value): bool
	{
		return Lib::arr()->type_arrpath(null, $value)->isOk();
	}


	public function arrpath_dot($value, ?string $dot = '.'): bool
	{
		return Lib::arr()->type_arrpath_dot(null, $value, $dot)->isOk();
	}


	/**
	 * > проверка на число, затем приведение к decimal, сначала делает numeric, потом приводит через moneytrunc
	 */
	public function decimal_moneytrunc($value, ?int $scale, array $refs = []): bool
	{
		return Lib::bcmath()->type_decimal_moneytrunc(null, $value, $scale, $refs)->isOk();
	}


	/**
	 * > проверка на число, затем приведение к decimal, сначала делает numeric, потом округляет через moneygrow
	 */
	public function decimal_moneygrow($value, ?int $scale, array $refs = []): bool
	{
		return Lib::bcmath()->type_decimal_moneygrow(null, $value, $scale, $refs)->isOk();
	}


	/**
	 * > проверка на число, затем приведение к decimal, сначала делает numeric, потом округляет через moneyceil
	 */
	public function decimal_moneyceil($value, ?int $scale, array $refs = []): bool
	{
		return Lib::bcmath()->type_decimal_moneyceil(null, $value, $scale, $refs)->isOk();
	}


	/**
	 * > проверка на число, затем приведение к decimal, сначала делает numeric, потом округляет через moneyfloor
	 */
	public function decimal_moneyfloor($value, ?int $scale, array $refs = []): bool
	{
		return Lib::bcmath()->type_decimal_moneyfloor(null, $value, $scale, $refs)->isOk();
	}


	public function bcnumber($value): bool
	{
		return Lib::bcmath()->type_bcnumber(null, $value)->isOk();
	}


	public function base($value, $alphabet): bool
	{
		return Lib::crypt()->type_base(null, $value, $alphabet)->isOk();
	}


	public function base_bin($value): bool
	{
		return Lib::crypt()->type_base_bin(null, $value)->isOk();
	}


	public function base_oct($value): bool
	{
		return Lib::crypt()->type_base_oct(null, $value)->isOk();
	}


	public function base_dec($value): bool
	{
		return Lib::crypt()->type_base_dec(null, $value)->isOk();
	}


	public function base_hex($value): bool
	{
		return Lib::crypt()->type_base_hex(null, $value)->isOk();
	}


	public function curl($value): bool
	{
		return Lib::curl()->type_curl(null, $value)->isOk();
	}


	public function curl_multi($value): bool
	{
		return Lib::curl()->type_curl_multi(null, $value)->isOk();
	}


	public function timezone($timezone, array $allowedTimezoneTypes = null): bool
	{
		return Lib::date()->type_timezone(null, $timezone, $allowedTimezoneTypes)->isOk();
	}


	public function timezone_offset($timezoneOrOffset): bool
	{
		return Lib::date()->type_timezone_offset(null, $timezoneOrOffset)->isOk();
	}


	public function timezone_abbr($timezoneOrAbbr): bool
	{
		return Lib::date()->type_timezone_abbr(null, $timezoneOrAbbr)->isOk();
	}


	public function timezone_name($timezoneOrName): bool
	{
		return Lib::date()->type_timezone_name(null, $timezoneOrName)->isOk();
	}


	public function timezone_nameabbr($timezoneOrNameOrAbbr): bool
	{
		return Lib::date()->type_timezone_nameabbr(null, $timezoneOrNameOrAbbr)->isOk();
	}


	public function interval($interval): bool
	{
		return Lib::date()->type_interval(null, $interval)->isOk();
	}


	public function interval_duration($duration): bool
	{
		return Lib::date()->type_interval_duration(null, $duration)->isOk();
	}


	public function interval_datestring($datestring): bool
	{
		return Lib::date()->type_interval_datestring(null, $datestring)->isOk();
	}


	public function interval_microtime($microtime): bool
	{
		return Lib::date()->type_interval_microtime(null, $microtime)->isOk();
	}


	public function interval_ago($date, \DateTimeInterface $from = null, bool $reverse = null): bool
	{
		return Lib::date()->type_interval_ago(null, $date, $from, $reverse)->isOk();
	}


	public function date($datestring, $timezoneFallback = null): bool
	{
		return Lib::date()->type_date(null, $datestring, $timezoneFallback)->isOk();
	}


	public function adate($datestring, $timezoneFallback = null): bool
	{
		return Lib::date()->type_adate(null, $datestring, $timezoneFallback)->isOk();
	}


	public function idate($datestring, $timezoneFallback = null): bool
	{
		return Lib::date()->type_idate(null, $datestring, $timezoneFallback)->isOk();
	}


	public function date_formatted($dateFormatted, $formats, $timezoneFallback = null): bool
	{
		return Lib::date()->type_date_formatted(null, $dateFormatted, $formats, $timezoneFallback)->isOk();
	}


	public function adate_formatted($dateFormatted, $formats, $timezoneFallback = null): bool
	{
		return Lib::date()->type_adate_formatted(null, $dateFormatted, $formats, $timezoneFallback)->isOk();
	}


	public function idate_formatted($dateFormatted, $formats, $timezoneFallback = null): bool
	{
		return Lib::date()->type_idate_formatted(null, $dateFormatted, $formats, $timezoneFallback)->isOk();
	}


	public function date_tz($datestring, array $allowedTimezoneTypes = null): bool
	{
		return Lib::date()->type_date_tz(null, $datestring, $allowedTimezoneTypes)->isOk();
	}


	public function adate_tz($datestring, array $allowedTimezoneTypes = null): bool
	{
		return Lib::date()->type_adate_tz(null, $datestring, $allowedTimezoneTypes)->isOk();
	}


	public function idate_tz($datestring, array $allowedTimezoneTypes = null): bool
	{
		return Lib::date()->type_idate_tz(null, $datestring, $allowedTimezoneTypes)->isOk();
	}


	public function date_tz_formatted($dateFormatted, $formats, array $allowedTimezoneTypes = null): bool
	{
		return Lib::date()->type_date_tz_formatted(null, $dateFormatted, $formats, $allowedTimezoneTypes)->isOk();
	}


	public function adate_tz_formatted($dateFormatted, $formats, array $allowedTimezoneTypes = null): bool
	{
		return Lib::date()->type_adate_tz_formatted(null, $dateFormatted, $formats, $allowedTimezoneTypes)->isOk();
	}


	public function idate_tz_formatted($dateFormatted, $formats, array $allowedTimezoneTypes = null): bool
	{
		return Lib::date()->type_idate_tz_formatted(null, $dateFormatted, $formats, $allowedTimezoneTypes)->isOk();
	}


	public function date_no_tz($datestring, $timezoneFallback = null): bool
	{
		return Lib::date()->type_date_no_tz(null, $datestring, $timezoneFallback)->isOk();
	}


	public function adate_no_tz($datestring, $timezoneFallback = null): bool
	{
		return Lib::date()->type_adate_no_tz(null, $datestring, $timezoneFallback)->isOk();
	}


	public function idate_no_tz($datestring, $timezoneFallback = null): bool
	{
		return Lib::date()->type_idate_no_tz(null, $datestring, $timezoneFallback)->isOk();
	}


	public function date_no_tz_formatted($dateFormatted, $formats, $timezoneFallback = null): bool
	{
		return Lib::date()->type_date_no_tz_formatted(null, $dateFormatted, $formats, $timezoneFallback)->isOk();
	}


	public function adate_no_tz_formatted($dateFormatted, $formats, $timezoneFallback = null): bool
	{
		return Lib::date()->type_adate_no_tz_formatted(null, $dateFormatted, $formats, $timezoneFallback)->isOk();
	}


	public function idate_no_tz_formatted($dateFormatted, $formats, $timezoneFallback = null): bool
	{
		return Lib::date()->type_idate_no_tz_formatted(null, $dateFormatted, $formats, $timezoneFallback)->isOk();
	}


	public function date_microtime($microtime, $timezoneSet = null): bool
	{
		return Lib::date()->type_date_microtime(null, $microtime, $timezoneSet)->isOk();
	}


	public function adate_microtime($microtime, $timezoneSet = null): bool
	{
		return Lib::date()->type_adate_microtime(null, $microtime, $timezoneSet)->isOk();
	}


	public function idate_microtime($microtime, $timezoneSet = null): bool
	{
		return Lib::date()->type_idate_microtime(null, $microtime, $timezoneSet)->isOk();
	}


	public function html_tag($value): bool
	{
		return Lib::format()->type_html_tag(null, $value)->isOk();
	}


	public function xml_tag($value): bool
	{
		return Lib::format()->type_xml_tag(null, $value)->isOk();
	}


	public function xml_nstag($value): bool
	{
		return Lib::format()->type_xml_nstag(null, $value)->isOk();
	}


	/**
	 * @param string $value
	 */
	public function chmod($value): bool
	{
		return Lib::fs()->type_chmod(null, $value)->isOk();
	}


	/**
	 * @param array{ 0: array|null } $refs
	 */
	public function realpath($value, bool $isAllowSymlink = null, array $refs = []): bool
	{
		return Lib::fs()->type_realpath(null, $value, $isAllowSymlink, $refs)->isOk();
	}


	public function freepath($value, array $refs = []): bool
	{
		return Lib::fs()->type_freepath(null, $value, $refs)->isOk();
	}


	public function freepath_normalized($value, string $separator = null, array $refs = []): bool
	{
		return Lib::fs()->type_freepath_normalized(null, $value, $separator, $refs)->isOk();
	}


	/**
	 * @param array{ 0: array|null } $refs
	 */
	public function dirpath($value, ?bool $isAllowExists, bool $isAllowSymlink = null, array $refs = []): bool
	{
		return Lib::fs()->type_dirpath(null, $value, $isAllowExists, $isAllowSymlink, $refs)->isOk();
	}


	/**
	 * @param array{ 0: array|null } $refs
	 */
	public function dirpath_realpath($value, bool $isAllowSymlink = null, array $refs = []): bool
	{
		return Lib::fs()->type_dirpath_realpath(null, $value, $isAllowSymlink, $refs)->isOk();
	}


	/**
	 * @param array{ 0: array|null } $refs
	 */
	public function filepath($value, ?bool $isAllowExists, bool $isAllowSymlink = null, array $refs = []): bool
	{
		return Lib::fs()->type_filepath(null, $value, $isAllowExists, $isAllowSymlink, $refs)->isOk();
	}


	/**
	 * @param array{ 0: array|null } $refs
	 */
	public function filepath_realpath($value, bool $isAllowSymlink = null, array $refs = []): bool
	{
		return Lib::fs()->type_filepath_realpath(null, $value, $isAllowSymlink, $refs)->isOk();
	}


	public function filename($value): bool
	{
		return Lib::fs()->type_filename(null, $value)->isOk();
	}


	public function file(
		$value,
		array $extensions = null,
		array $mimeTypes = null,
		array $filters = null,
		array $refs = []
	): bool {
		return Lib::fs()->type_file(null, $value, $extensions, $mimeTypes, $filters, $refs)->isOk();
	}


	public function image(
		$value,
		array $extensions = null,
		array $mimeTypes = null,
		array $filters = null,
		array $refs = []
	): bool {
		return Lib::fs()->type_image(null, $value, $extensions, $mimeTypes, $filters, $refs)->isOk();
	}


	public function socket($value): bool
	{
		return Lib::fs()->type_socket(null, $value)->isOk();
	}


	public function stream($value): bool
	{
		return Lib::fs()->type_stream(null, $value)->isOk();
	}


	public function http_method($value): bool
	{
		return Lib::http()->type_http_method(null, $value)->isOk();
	}


	public function address_ip($value): bool
	{
		return Lib::net()->type_address_ip(null, $value)->isOk();
	}


	public function address_ip_v4($value): bool
	{
		return Lib::net()->type_address_ip_v4(null, $value)->isOk();
	}


	public function address_ip_v6($value): bool
	{
		return Lib::net()->type_address_ip_v6(null, $value)->isOk();
	}


	public function address_mac($value): bool
	{
		return Lib::net()->type_address_mac(null, $value)->isOk();
	}


	public function subnet($value, string $ipFallback = null): bool
	{
		return Lib::net()->type_subnet(null, $value, $ipFallback)->isOk();
	}


	public function subnet_v4($value, string $ipFallback = null): bool
	{
		return Lib::net()->type_subnet_v4(null, $value, $ipFallback)->isOk();
	}


	public function subnet_v6($value, string $ipFallback = null): bool
	{
		return Lib::net()->type_subnet_v6(null, $value, $ipFallback)->isOk();
	}


	protected function subnet_v4_iplike($value): bool
	{
		return Lib::net()->type_subnet_v4_iplike(null, $value)->isOk();
	}


	public function php_num($value): bool
	{
		return Lib::num()->type_php_num(null, $value)->isOk();
	}


	public function php_int($value): bool
	{
		return Lib::num()->type_php_int(null, $value)->isOk();
	}


	public function php_float($value): bool
	{
		return Lib::num()->type_php_float(null, $value)->isOk();
	}


	public function nan($value): bool
	{
		return Lib::num()->type_nan(null, $value)->isOk();
	}


	public function php_float_not_nan($value): bool
	{
		return Lib::num()->type_php_float_not_nan(null, $value)->isOk();
	}


	public function float_not_nan($value): bool
	{
		return Lib::num()->type_float_not_nan(null, $value)->isOk();
	}


	public function any_not_nan($value): bool
	{
		return Lib::num()->type_any_not_nan(null, $value)->isOk();
	}


	public function infinite($value): bool
	{
		return Lib::num()->type_infinite(null, $value)->isOk();
	}


	public function php_float_not_infinite($value): bool
	{
		return Lib::num()->type_php_float_not_infinite(null, $value)->isOk();
	}


	public function float_not_infinite($value): bool
	{
		return Lib::num()->type_float_not_infinite(null, $value)->isOk();
	}


	public function any_not_infinite($value): bool
	{
		return Lib::num()->type_any_not_infinite(null, $value)->isOk();
	}


	public function finite($value): bool
	{
		return Lib::num()->type_finite(null, $value)->isOk();
	}


	public function php_float_not_finite($value): bool
	{
		return Lib::num()->type_php_float_not_finite(null, $value)->isOk();
	}


	public function float_not_finite($value): bool
	{
		return Lib::num()->type_float_not_finite(null, $value)->isOk();
	}


	public function any_not_finite($value): bool
	{
		return Lib::num()->type_any_not_finite(null, $value)->isOk();
	}


	public function float_min($value): bool
	{
		return Lib::num()->type_float_min(null, $value)->isOk();
	}


	public function float_not_float_min($value): bool
	{
		return Lib::num()->type_float_not_float_min(null, $value)->isOk();
	}


	public function any_not_float_min($value): bool
	{
		return Lib::num()->type_any_not_float_min(null, $value)->isOk();
	}


	public function numeric($value, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric(null, $value, $isAllowExp, $refs)->isOk();
	}


	public function numeric_int($value, array $refs = []): bool
	{
		return Lib::num()->type_numeric_int(null, $value, $refs)->isOk();
	}


	public function numeric_float($value, array $refs = []): bool
	{
		return Lib::num()->type_numeric_float(null, $value, $refs)->isOk();
	}


	public function numeric_non_zero($value, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_non_zero(null, $value, $isAllowExp, $refs)->isOk();
	}


	public function numeric_non_negative($value, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_non_negative(null, $value, $isAllowExp, $refs)->isOk();
	}


	public function numeric_non_positive($value, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_non_positive(null, $value, $isAllowExp, $refs)->isOk();
	}


	public function numeric_negative($value, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_negative(null, $value, $isAllowExp, $refs)->isOk();
	}


	public function numeric_positive($value, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_positive(null, $value, $isAllowExp, $refs)->isOk();
	}


	public function numeric_zero_plus_minus_one($value, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_zero_plus_minus_one(null, $value, $isAllowExp, $refs)->isOk();
	}


	public function numeric_non_negative_or_minus_one($value, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_non_negative_or_minus_one(null, $value, $isAllowExp, $refs)->isOk();
	}


	public function numeric_positive_or_minus_one($value, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_positive_or_minus_one(null, $value, $isAllowExp, $refs)->isOk();
	}


	public function numeric_gt($value, $gt, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_gt(null, $value, $gt, $isAllowExp, $refs)->isOk();
	}


	public function numeric_gte($value, $gte, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_gte(null, $value, $gte, $isAllowExp, $refs)->isOk();
	}


	public function numeric_lt($value, $lt, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_lt(null, $value, $lt, $isAllowExp, $refs)->isOk();
	}


	public function numeric_lte($value, $lte, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_lte(null, $value, $lte, $isAllowExp, $refs)->isOk();
	}


	public function numeric_between($value, $from, $to, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_between(null, $value, $from, $to, $isAllowExp, $refs)->isOk();
	}


	public function numeric_inside($value, $from, $to, bool $isAllowExp = null, array $refs = []): bool
	{
		return Lib::num()->type_numeric_inside(null, $value, $from, $to, $isAllowExp, $refs)->isOk();
	}


	public function num($value): bool
	{
		return Lib::num()->type_num(null, $value)->isOk();
	}


	public function int($value): bool
	{
		return Lib::num()->type_int(null, $value)->isOk();
	}


	public function float($value): bool
	{
		return Lib::num()->type_float(null, $value)->isOk();
	}


	public function num_non_zero($value): bool
	{
		return Lib::num()->type_num_non_zero(null, $value)->isOk();
	}


	public function num_non_negative($value): bool
	{
		return Lib::num()->type_num_non_negative(null, $value)->isOk();
	}


	public function num_non_positive($value): bool
	{
		return Lib::num()->type_num_non_positive(null, $value)->isOk();
	}


	public function num_negative($value): bool
	{
		return Lib::num()->type_num_negative(null, $value)->isOk();
	}


	public function num_positive($value): bool
	{
		return Lib::num()->type_num_positive(null, $value)->isOk();
	}


	public function num_zero_plus_minus_one($value): bool
	{
		return Lib::num()->type_num_zero_plus_minus_one(null, $value)->isOk();
	}


	public function num_non_negative_or_minus_one($value): bool
	{
		return Lib::num()->type_num_non_negative_or_minus_one(null, $value)->isOk();
	}


	public function num_positive_or_minus_one($value): bool
	{
		return Lib::num()->type_num_positive_or_minus_one(null, $value)->isOk();
	}


	public function num_gt($value, $gt): bool
	{
		return Lib::num()->type_num_gt(null, $value, $gt)->isOk();
	}


	public function num_gte($value, $gte): bool
	{
		return Lib::num()->type_num_gte(null, $value, $gte)->isOk();
	}


	public function num_lt($value, $lt): bool
	{
		return Lib::num()->type_num_lt(null, $value, $lt)->isOk();
	}


	public function num_lte($value, $lte): bool
	{
		return Lib::num()->type_num_lte(null, $value, $lte)->isOk();
	}


	public function num_between($value, $from, $to): bool
	{
		return Lib::num()->type_num_between(null, $value, $from, $to)->isOk();
	}


	public function num_inside($value, $from, $to): bool
	{
		return Lib::num()->type_num_inside(null, $value, $from, $to)->isOk();
	}


	public function int_non_zero($value): bool
	{
		return Lib::num()->type_int_non_zero(null, $value)->isOk();
	}


	public function int_non_negative($value): bool
	{
		return Lib::num()->type_int_non_negative(null, $value)->isOk();
	}


	public function int_non_positive($value): bool
	{
		return Lib::num()->type_int_non_positive(null, $value)->isOk();
	}


	public function int_negative($value): bool
	{
		return Lib::num()->type_int_negative(null, $value)->isOk();
	}


	public function int_positive($value): bool
	{
		return Lib::num()->type_int_positive(null, $value)->isOk();
	}


	public function int_zero_plus_minus_one($value): bool
	{
		return Lib::num()->type_int_zero_plus_minus_one(null, $value)->isOk();
	}


	public function int_non_negative_or_minus_one($value): bool
	{
		return Lib::num()->type_int_non_negative_or_minus_one(null, $value)->isOk();
	}


	public function int_positive_or_minus_one($value): bool
	{
		return Lib::num()->type_int_positive_or_minus_one(null, $value)->isOk();
	}


	public function int_gt($value, $gt): bool
	{
		return Lib::num()->type_int_gt(null, $value, $gt)->isOk();
	}


	public function int_gte($value, $gte): bool
	{
		return Lib::num()->type_int_gte(null, $value, $gte)->isOk();
	}


	public function int_lt($value, $lt): bool
	{
		return Lib::num()->type_int_lt(null, $value, $lt)->isOk();
	}


	public function int_lte($value, $lte): bool
	{
		return Lib::num()->type_int_lte(null, $value, $lte)->isOk();
	}


	public function int_between($value, $from, $to): bool
	{
		return Lib::num()->type_int_between(null, $value, $from, $to)->isOk();
	}


	public function int_inside($value, $from, $to): bool
	{
		return Lib::num()->type_int_inside(null, $value, $from, $to)->isOk();
	}


	public function float_non_zero($value): bool
	{
		return Lib::num()->type_float_non_zero(null, $value)->isOk();
	}


	public function float_non_negative($value): bool
	{
		return Lib::num()->type_float_non_negative(null, $value)->isOk();
	}


	public function float_non_positive($value): bool
	{
		return Lib::num()->type_float_non_positive(null, $value)->isOk();
	}


	public function float_negative($value): bool
	{
		return Lib::num()->type_float_negative(null, $value)->isOk();
	}


	public function float_positive($value): bool
	{
		return Lib::num()->type_float_positive(null, $value)->isOk();
	}


	public function float_zero_plus_minus_one($value): bool
	{
		return Lib::num()->type_float_zero_plus_minus_one(null, $value)->isOk();
	}


	public function float_non_negative_or_minus_one($value): bool
	{
		return Lib::num()->type_float_non_negative_or_minus_one(null, $value)->isOk();
	}


	public function float_positive_or_minus_one($value): bool
	{
		return Lib::num()->type_float_positive_or_minus_one(null, $value)->isOk();
	}


	public function float_gt($value, $gt): bool
	{
		return Lib::num()->type_float_gt(null, $value, $gt)->isOk();
	}


	public function float_gte($value, $gte): bool
	{
		return Lib::num()->type_float_gte(null, $value, $gte)->isOk();
	}


	public function float_lt($value, $lt): bool
	{
		return Lib::num()->type_float_lt(null, $value, $lt)->isOk();
	}


	public function float_lte($value, $lte): bool
	{
		return Lib::num()->type_float_lte(null, $value, $lte)->isOk();
	}


	public function float_between($value, $from, $to): bool
	{
		return Lib::num()->type_float_between(null, $value, $from, $to)->isOk();
	}


	public function float_inside($value, $from, $to): bool
	{
		return Lib::num()->type_float_inside(null, $value, $from, $to)->isOk();
	}


	/**
	 * > проверка на decimal, строгая. Если число представлено вида 1.12317239871927391273 и стоит ограничение 2 знака - не преобразует, а бросит ошибку
	 *
	 * 1.5 -> (2) -> '1.50'
	 * 1.500 -> (2) -> '1.50'
	 * 1.501 -> (2) -> [ERROR]
	 */
	public function decimal($value, ?int $scale, array $refs = []): bool
	{
		return Lib::num()->type_decimal(null, $value, $scale, $refs)->isOk();
	}


	public function number($value, bool $isAllowExp = null): bool
	{
		return Lib::num()->type_number(null, $value, $isAllowExp)->isOk();
	}


	public function exponent($value): bool
	{
		return Lib::num()->type_exponent(null, $value)->isOk();
	}


	public function scale($value): bool
	{
		return Lib::num()->type_scale(null, $value)->isOk();
	}


	public function percent($value): bool
	{
		return Lib::num()->type_percent(null, $value)->isOk();
	}


	public function percent_numeric($value): bool
	{
		return Lib::num()->type_percent_numeric(null, $value)->isOk();
	}


	public function ratio($value): bool
	{
		return Lib::num()->type_ratio(null, $value)->isOk();
	}


	public function ratio_numeric($value): bool
	{
		return Lib::num()->type_ratio_numeric(null, $value)->isOk();
	}


	/**
	 * > Специальный тип-синоним NULL, переданный пользователем через API, например '{N}'
	 * > в случаях, когда NULL интерпретируется как "не трогать", а NIL как "очистить"
	 *
	 * > NAN не равен ничему даже самому себе
	 * > NIL равен только самому себе
	 * > NULL означает пустоту и им можно заменить значения '', [], `resource (closed)`, NIL, но нельзя заменить NAN
	 */
	public function nil($value): bool
	{
		return Lib::php()->type_nil(null, $value)->isOk();
	}


	public function not_nil($value): bool
	{
		return Lib::php()->type_not_nil(null, $value)->isOk();
	}


	public function null($value): bool
	{
		return Lib::php()->type_null(null, $value)->isOk();
	}


	public function not_null($value): bool
	{
		return Lib::php()->type_not_null(null, $value)->isOk();
	}


	public function empty($value): bool
	{
		return Lib::php()->type_empty(null, $value)->isOk();
	}


	public function not_empty($value): bool
	{
		return Lib::php()->type_not_empty(null, $value)->isOk();
	}


	/**
	 * > Специальный тип, который значит, что значение можно отбросить или не учитывать, т.к. оно не несёт информации
	 */
	public function blank($value): bool
	{
		return Lib::php()->type_blank(null, $value)->isOk();
	}


	public function not_blank($value): bool
	{
		return Lib::php()->type_not_blank(null, $value)->isOk();
	}


	/**
	 * > Специальный тип, который значит, что значение можно заменить NULL-ом
	 */
	public function nullable($value): bool
	{
		return Lib::php()->type_nullable(null, $value)->isOk();
	}


	public function not_nullable($value): bool
	{
		return Lib::php()->type_not_nullable(null, $value)->isOk();
	}


	/**
	 * > Специальный тип, который значит, что значение было отправлено клиентом, а не появилось из PHP
	 */
	public function passed($value): bool
	{
		return Lib::php()->type_passed(null, $value)->isOk();
	}


	public function not_passed($value): bool
	{
		return Lib::php()->type_not_passed(null, $value)->isOk();
	}


	/**
	 * @noinspection PhpConditionAlreadyCheckedInspection
	 */
	public function php_bool($value): bool
	{
		return Lib::php()->type_php_bool(null, $value)->isOk();
	}


	public function php_bool_false($value): bool
	{
		return Lib::php()->type_php_bool_false(null, $value)->isOk();
	}


	/**
	 * @noinspection PhpConditionAlreadyCheckedInspection
	 */
	public function php_bool_true($value): bool
	{
		return Lib::php()->type_php_bool_true(null, $value)->isOk();
	}


	/**
	 * @noinspection PhpConditionAlreadyCheckedInspection
	 */
	public function not_php_bool($value): bool
	{
		return Lib::php()->type_not_php_bool(null, $value)->isOk();
	}


	public function bool($value): bool
	{
		return Lib::php()->type_bool(null, $value)->isOk();
	}


	public function bool_false($value): bool
	{
		return Lib::php()->type_bool_false(null, $value)->isOk();
	}


	public function bool_true($value): bool
	{
		return Lib::php()->type_bool_true(null, $value)->isOk();
	}


	public function not_bool($value): bool
	{
		return Lib::php()->type_not_bool(null, $value)->isOk();
	}


	public function userbool($value): bool
	{
		return Lib::php()->type_userbool(null, $value)->isOk();
	}


	public function userbool_false($value): bool
	{
		return Lib::php()->type_userbool_false(null, $value)->isOk();
	}


	public function userbool_true($value): bool
	{
		return Lib::php()->type_userbool_true(null, $value)->isOk();
	}


	public function not_userbool($value): bool
	{
		return Lib::php()->type_not_userbool(null, $value)->isOk();
	}


	public function object($value): bool
	{
		return Lib::php()->type_object(null, $value)->isOk();
	}


	public function not_object($value): bool
	{
		return Lib::php()->type_not_object(null, $value)->isOk();
	}


	public function stdclass($value): bool
	{
		return Lib::php()->type_stdclass(null, $value)->isOk();
	}


	public function not_stdclass($value): bool
	{
		return Lib::php()->type_not_stdclass(null, $value)->isOk();
	}


	/**
	 * @template-covariant T
	 *
	 * @param object          $value
	 * @param class-string<T> $className
	 */
	public function instance_of($value, string $className, array $refs = []): bool
	{
		return Lib::php()->type_instance_of(null, $value, $className, $refs)->isOk();
	}


	/**
	 * @template-covariant T
	 *
	 * @param object|class-string $value
	 * @param class-string<T>     $className
	 */
	public function is_a($value, string $className, bool $allowString = null, $refs = []): bool
	{
		return Lib::php()->type_is_a(null, $value, $className, $allowString, $refs)->isOk();
	}


	/**
	 * @template-covariant T
	 *
	 * @param object|class-string $value
	 * @param class-string<T>     $className
	 */
	public function is_subclass_of($value, string $className, bool $allowString = null, array $refs = []): bool
	{
		return Lib::php()->type_is_subclass_of(null, $value, $className, $allowString, $refs)->isOk();
	}


	/**
	 * @template-covariant T
	 *
	 * @param object|class-string $value
	 * @param class-string<T>     $className
	 */
	public function is_class_of($value, string $className, bool $allowString = null, array $refs = []): bool
	{
		return Lib::php()->type_is_class_of(null, $value, $className, $allowString, $refs)->isOk();
	}


	public function countable($value): bool
	{
		return Lib::php()->type_countable(null, $value)->isOk();
	}


	public function countable_object($value): bool
	{
		return Lib::php()->type_countable_object(null, $value)->isOk();
	}


	public function sizeable($value): bool
	{
		return Lib::php()->type_sizeable(null, $value)->isOk();
	}


	/**
	 * @template-covariant T of object
	 *
	 * @param class-string<T>|T|mixed $value
	 */
	public function struct_exists($value, int $flags = null): bool
	{
		return Lib::php()->type_struct_exists(null, $value, $flags)->isOk();
	}


	/**
	 * @template-covariant T of object
	 *
	 * @param class-string<T>|T|mixed $value
	 */
	public function struct($value, int $flags = null): bool
	{
		return Lib::php()->type_struct(null, $value, $flags)->isOk();
	}


	/**
	 * @template-covariant T of object
	 *
	 * @param class-string<T>|T|mixed $value
	 */
	public function struct_class($value, int $flags = null): bool
	{
		return Lib::php()->type_struct_class(null, $value, $flags)->isOk();
	}


	public function struct_interface($value, int $flags = null): bool
	{
		return Lib::php()->type_struct_interface(null, $value, $flags)->isOk();
	}


	public function struct_trait($value, int $flags = null): bool
	{
		return Lib::php()->type_struct_trait(null, $value, $flags)->isOk();
	}


	/**
	 * @template-covariant T of \UnitEnum
	 *
	 * @param class-string<T>|T|mixed $value
	 */
	public function struct_enum($value, int $flags = null): bool
	{
		return Lib::php()->type_struct_enum(null, $value, $flags)->isOk();
	}


	/**
	 * @template-covariant T of object
	 *
	 * @param class-string<T>|T|mixed $value
	 */
	public function struct_fqcn($value, int $flags = null): bool
	{
		return Lib::php()->type_struct_fqcn(null, $value, $flags)->isOk();
	}


	public function struct_namespace($value, int $flags = null): bool
	{
		return Lib::php()->type_struct_namespace(null, $value, $flags)->isOk();
	}


	public function struct_basename($value, int $flags = null): bool
	{
		return Lib::php()->type_struct_basename(null, $value, $flags)->isOk();
	}


	public function resource($value, string $resourceType = null): bool
	{
		return Lib::php()->type_resource(null, $value, $resourceType)->isOk();
	}


	public function resource_opened($value, string $resourceType = null): bool
	{
		return Lib::php()->type_resource_opened(null, $value, $resourceType)->isOk();
	}


	public function resource_closed($value): bool
	{
		return Lib::php()->type_resource_closed(null, $value)->isOk();
	}


	public function not_resource($value): bool
	{
		return Lib::php()->type_not_resource(null, $value)->isOk();
	}


	/**
	 * @template-covariant T of \UnitEnum
	 *
	 * @param T|int|string         $value
	 * @param class-string<T>|null $enumClass
	 */
	public function enum_case($value, string $enumClass = null): bool
	{
		return Lib::php()->type_enum_case(null, $value, $enumClass)->isOk();
	}


	/**
	 * > метод не всегда callable, поскольку строка 'class->method' не является callable
	 * > метод не всегда callable, поскольку массив [ 'class', 'method' ] не является callable, если метод публичный
	 * > используйте type_callable_string, если собираетесь вызывать метод
	 * > используйте type_callable_array, если собираетесь вызывать метод
	 *
	 * @param array{ 0?: array{ 0: class-string, 1: string }, 1?: string } $refs
	 */
	public function method($value, array $refs = []): bool
	{
		return Lib::php()->type_method(null, $value, $refs)->isOk();
	}


	/**
	 * > метод не всегда callable, поскольку строка 'class->method' не является callable
	 * > метод не всегда callable, поскольку массив [ 'class', 'method' ] не является callable, если метод публичный
	 * > используйте type_callable_string, если собираетесь вызывать метод
	 * > используйте type_callable_array, если собираетесь вызывать метод
	 */
	public function method_array($value): bool
	{
		return Lib::php()->type_method_array(null, $value)->isOk();
	}


	/**
	 * > метод не всегда callable, поскольку строка 'class->method' не является callable
	 * > метод не всегда callable, поскольку массив [ 'class', 'method' ] не является callable, если метод публичный
	 * > используйте type_callable_string, если собираетесь вызывать метод
	 * > используйте type_callable_array, если собираетесь вызывать метод
	 */
	public function method_string($value): bool
	{
		return Lib::php()->type_method_string(null, $value)->isOk();
	}


	/**
	 * > в версиях PHP до 8.0.0 публичный метод считался callable, если его проверить даже на имени класса
	 * > при этом вызвать MyClass::publicMethod было нельзя, т.к. вызываемым является только MyClass::publicStaticMethod
	 *
	 * @param string|object $newScope
	 */
	public function callable($value, $newScope = 'static'): bool
	{
		return Lib::php()->type_callable(null, $value, $newScope)->isOk();
	}


	public function callable_object($value, $newScope = 'static'): bool
	{
		return Lib::php()->type_callable_object(null, $value, $newScope)->isOk();
	}


	public function callable_object_closure($value, $newScope = 'static'): bool
	{
		return Lib::php()->type_callable_object_closure(null, $value, $newScope)->isOk();
	}


	public function callable_object_invokable($value, $newScope = 'static'): bool
	{
		return Lib::php()->type_callable_object_invokable(null, $value, $newScope)->isOk();
	}


	/**
	 * @param string|object $newScope
	 */
	public function callable_array($value, $newScope = 'static'): bool
	{
		return Lib::php()->type_callable_array(null, $value, $newScope)->isOk();
	}


	/**
	 * @param string|object $newScope
	 */
	public function callable_array_method($value, $newScope = 'static'): bool
	{
		return Lib::php()->type_callable_array_method(null, $value, $newScope)->isOk();
	}


	/**
	 * @param string|object $newScope
	 */
	public function callable_array_method_static($value, $newScope = 'static'): bool
	{
		return Lib::php()->type_callable_array_method_static(null, $value, $newScope)->isOk();
	}


	/**
	 * @param string|object $newScope
	 */
	public function callable_array_method_non_static($value, $newScope = 'static'): bool
	{
		return Lib::php()->type_callable_array_method_non_static(null, $value, $newScope)->isOk();
	}


	public function callable_string($value, $newScope = 'static'): bool
	{
		return Lib::php()->type_callable_string(null, $value, $newScope)->isOk();
	}


	public function callable_string_function($value): bool
	{
		return Lib::php()->type_callable_string_function(null, $value)->isOk();
	}


	public function callable_string_function_internal($value): bool
	{
		return Lib::php()->type_callable_string_function_internal(null, $value)->isOk();
	}


	public function callable_string_function_non_internal($value): bool
	{
		return Lib::php()->type_callable_string_function_non_internal(null, $value)->isOk();
	}


	public function callable_string_method_static($value, $newScope = 'static'): bool
	{
		return Lib::php()->type_callable_string_method_static(null, $value, $newScope)->isOk();
	}


	/**
	 * @param array{ 0: array|null } $refs
	 */
	public function path($value, array $refs = []): bool
	{
		return Lib::php()->type_path(null, $value, $refs)->isOk();
	}


	/**
	 * @param array{ 0: array|null } $refs
	 */
	public function path_normalized($value, string $separator = null, array $refs = []): bool
	{
		return Lib::php()->type_path_normalized(null, $value, $separator, $refs)->isOk();
	}


	public function locale($value, array $refs = []): bool
	{
		return Lib::php()->type_locale(null, $value, $refs)->isOk();
	}


	public function locale_ietf($value, array $refs = []): bool
	{
		return Lib::php()->type_locale_ietf(null, $value, $refs)->isOk();
	}


	public function locale_posix($value, array $refs = []): bool
	{
		return Lib::php()->type_locale_posix(null, $value, $refs)->isOk();
	}


	public function count_gt($value, $gt): bool
	{
		return Lib::php()->type_count_gt(null, $value, $gt)->isOk();
	}


	public function count_gte($value, $gte): bool
	{
		return Lib::php()->type_count_gte(null, $value, $gte)->isOk();
	}


	public function count_lt($value, $lt): bool
	{
		return Lib::php()->type_count_lt(null, $value, $lt)->isOk();
	}


	public function count_lte($value, $lte): bool
	{
		return Lib::php()->type_count_lte(null, $value, $lte)->isOk();
	}


	public function count_between($value, $from, $to): bool
	{
		return Lib::php()->type_count_between(null, $value, $from, $to)->isOk();
	}


	public function count_inside($value, $from, $to): bool
	{
		return Lib::php()->type_count_inside(null, $value, $from, $to)->isOk();
	}


	public function regex($value): bool
	{
		return Lib::preg()->type_regex(null, $value)->isOk();
	}


	public function regexp($value, string $enclosure = '/', string $flags = null): bool
	{
		return Lib::preg()->type_regexp(null, $value, $enclosure, $flags)->isOk();
	}


	public function uuid_nil($value): bool
	{
		return Lib::random()->type_uuid_nil(null, $value)->isOk();
	}


	public function uuid($value): bool
	{
		return Lib::random()->type_uuid(null, $value)->isOk();
	}


	public function uuid_not_nil($value): bool
	{
		return Lib::random()->type_uuid_not_nil(null, $value)->isOk();
	}


	public function uuid_v4($value): bool
	{
		return Lib::random()->type_uuid_v4(null, $value)->isOk();
	}


	public function uuid_v5($value): bool
	{
		return Lib::random()->type_uuid_v5(null, $value)->isOk();
	}


	public function uuid_v7($value): bool
	{
		return Lib::random()->type_uuid_v7(null, $value)->isOk();
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 */
	public function email($value, array $filters = null, array $refs = []): bool
	{
		return Lib::social()->type_email(null, $value, $filters, $refs)->isOk();
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 */
	public function email_fake($value, array $refs = []): bool
	{
		return Lib::social()->type_email_fake(null, $value, $refs)->isOk();
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 */
	public function email_non_fake($value, array $filters = null, array $refs = []): bool
	{
		return Lib::social()->type_email_non_fake(null, $value, $filters, $refs)->isOk();
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 */
	public function email_maybe_fake($value, array $filters = null, array $refs = []): bool
	{
		return Lib::social()->type_email_maybe_fake(null, $value, $filters, $refs)->isOk();
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 */
	public function phone($value, array $refs = []): bool
	{
		return Lib::social()->type_phone(null, $value, $refs)->isOk();
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 */
	public function phone_fake($value, array $refs = []): bool
	{
		return Lib::social()->type_phone_fake(null, $value, $refs)->isOk();
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 */
	public function phone_non_fake($value, array $refs = []): bool
	{
		return Lib::social()->type_phone_non_fake(null, $value, $refs)->isOk();
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 */
	public function phone_maybe_fake($value, array $refs = []): bool
	{
		return Lib::social()->type_phone_maybe_fake(null, $value, $refs)->isOk();
	}


	/**
	 * > использует библиотеку libphonenumber, чтобы убедится, что телефон соответствует стандартам Google
	 *
	 * @param array{ 0?: string, 1?: string, 2?: string, 3?: string } $refs
	 */
	public function phone_real($value, ?string $region = '', array $refs = []): bool
	{
		return Lib::social()->type_phone_real(null, $value, $region, $refs)->isOk();
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 */
	public function tel($value, array $refs = []): bool
	{
		return Lib::social()->type_tel(null, $value, $refs)->isOk();
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 */
	public function tel_fake($value, array $refs = []): bool
	{
		return Lib::social()->type_tel_fake(null, $value, $refs)->isOk();
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 */
	public function tel_non_fake($value, array $refs = []): bool
	{
		return Lib::social()->type_tel_non_fake(null, $value, $refs)->isOk();
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 */
	public function tel_maybe_fake($value, array $refs = []): bool
	{
		return Lib::social()->type_tel_maybe_fake(null, $value, $refs)->isOk();
	}


	/**
	 * > использует библиотеку libphonenumber, чтобы убедится, что телефон соответствует стандартам Google
	 *
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 */
	public function tel_real($value, ?string $region = '', array $refs = []): bool
	{
		return Lib::social()->type_tel_real(null, $value, $region, $refs)->isOk();
	}


	public function php_string($value): bool
	{
		return Lib::str()->type_php_string(null, $value)->isOk();
	}


	public function php_string_empty($value): bool
	{
		return Lib::str()->type_php_string_empty(null, $value)->isOk();
	}


	public function php_string_not_empty($value): bool
	{
		return Lib::str()->type_php_string_not_empty(null, $value)->isOk();
	}


	public function string($value): bool
	{
		return Lib::str()->type_string(null, $value)->isOk();
	}


	public function string_empty($value): bool
	{
		return Lib::str()->type_string_empty(null, $value)->isOk();
	}


	public function string_not_empty($value): bool
	{
		return Lib::str()->type_string_not_empty(null, $value)->isOk();
	}


	public function strlen_gt($value, $gt): bool
	{
		return Lib::str()->type_strlen_gt(null, $value, $gt)->isOk();
	}


	public function strlen_gte($value, $gte): bool
	{
		return Lib::str()->type_strlen_gte(null, $value, $gte)->isOk();
	}


	public function strlen_lt($value, $lt): bool
	{
		return Lib::str()->type_strlen_lt(null, $value, $lt)->isOk();
	}


	public function strlen_lte($value, $lte): bool
	{
		return Lib::str()->type_strlen_lte(null, $value, $lte)->isOk();
	}


	public function strlen_between($value, $from, $to): bool
	{
		return Lib::str()->type_strlen_between(null, $value, $from, $to)->isOk();
	}


	public function strlen_inside($value, $from, $to): bool
	{
		return Lib::str()->type_strlen_inside(null, $value, $from, $to)->isOk();
	}


	public function strsize_gt($value, $gt): bool
	{
		return Lib::str()->type_strsize_gt(null, $value, $gt)->isOk();
	}


	public function strsize_gte($value, $gte): bool
	{
		return Lib::str()->type_strsize_gte(null, $value, $gte)->isOk();
	}


	public function strsize_lt($value, $lt): bool
	{
		return Lib::str()->type_strsize_lt(null, $value, $lt)->isOk();
	}


	public function strsize_lte($value, $lte): bool
	{
		return Lib::str()->type_strsize_lte(null, $value, $lte)->isOk();
	}


	public function strsize_between($value, $from, $to): bool
	{
		return Lib::str()->type_strsize_between(null, $value, $from, $to)->isOk();
	}


	public function strsize_inside($value, $from, $to): bool
	{
		return Lib::str()->type_strsize_inside(null, $value, $from, $to)->isOk();
	}


	/**
	 * > применяет ltrim к переменной (приводит к строке), после чего проверяет не стала ли переменная пустой строкой
	 */
	public function ltrim($value, string $characters = null): bool
	{
		return Lib::str()->type_ltrim(null, $value, $characters)->isOk();
	}


	/**
	 * > применяет rtrim к переменной (приводит к строке), после чего проверяет не стала ли переменная пустой строкой
	 */
	public function rtrim($value, string $characters = null): bool
	{
		return Lib::str()->type_rtrim(null, $value, $characters)->isOk();
	}


	/**
	 * > применяет trim к переменной (приводит к строке), после чего проверяет не стала ли переменная пустой строкой
	 */
	public function trim($value, string $characters = null): bool
	{
		return Lib::str()->type_trim(null, $value, $characters)->isOk();
	}


	/**
	 * > применяет lcrop к переменной (приводит к строке), после чего проверяет не стала ли переменная пустой строкой
	 */
	public function lcrop($value, $needleList = null): bool
	{
		return Lib::str()->type_lcrop(null, $value, $needleList)->isOk();
	}


	/**
	 * > применяет rcrop к переменной (приводит к строке), после чего проверяет не стала ли переменная пустой строкой
	 */
	public function rcrop($value, $needleList = null): bool
	{
		return Lib::str()->type_rcrop(null, $value, $needleList)->isOk();
	}


	/**
	 * > применяет crop к переменной (приводит к строке), после чего проверяет не стала ли переменная пустой строкой
	 */
	public function crop($value, $needleList = null): bool
	{
		return Lib::str()->type_crop(null, $value, $needleList)->isOk();
	}


	public function char($value): bool
	{
		return Lib::str()->type_char(null, $value)->isOk();
	}


	public function letter($value): bool
	{
		return Lib::str()->type_letter(null, $value)->isOk();
	}


	public function word($value): bool
	{
		return Lib::str()->type_word(null, $value)->isOk();
	}


	public function alphabet($value): bool
	{
		return Lib::str()->type_alphabet(null, $value)->isOk();
	}


	public function ctype_digit($value): bool
	{
		return Lib::str()->type_ctype_digit(null, $value)->isOk();
	}


	public function ctype_alpha($value, bool $allowUpperCase = null): bool
	{
		return Lib::str()->type_ctype_alpha(null, $value, $allowUpperCase)->isOk();
	}


	public function ctype_alnum($value, bool $allowUpperCase = null): bool
	{
		return Lib::str()->type_ctype_alnum(null, $value, $allowUpperCase)->isOk();
	}


	/**
	 * > https://example.com:8080/example#example?example=1
	 * > /example#example?example=1
	 *
	 * @param string|true             $url
	 * @param string|false|array|null $query
	 * @param string|false|null       $fragment
	 */
	public function uri(
		$url,
		$query = null,
		$fragment = null,
		int $isHostIdnaAscii = null,
		int $isLinkUrlencoded = null,
		array $refs = []
	): bool {
		return Lib::url()->type_uri(null, $url, $query, $fragment, $isHostIdnaAscii, $isLinkUrlencoded, $refs)->isOk();
	}


	/**
	 * > https://example.com:8080/example#example?example=1
	 *
	 * @param string|true             $url
	 * @param string|false|array|null $query
	 * @param string|false|null       $fragment
	 */
	public function url(
		$url,
		$query = null,
		$fragment = null,
		int $isHostIdnaAscii = null,
		int $isLinkUrlencoded = null,
		array $refs = []
	): bool {
		return Lib::url()->type_url(null, $url, $query, $fragment, $isHostIdnaAscii, $isLinkUrlencoded, $refs)->isOk();
	}


	/**
	 * > /example#example?example=1
	 *
	 * @param string|true             $url
	 * @param string|false|array|null $query
	 * @param string|false|null       $fragment
	 */
	public function link($url, $query = null, $fragment = null, int $isLinkUrlencoded = null, array $refs = []): bool
	{
		return Lib::url()->type_link(null, $url, $query, $fragment, $isLinkUrlencoded, $refs)->isOk();
	}


	/**
	 * > https://example.com:8080/
	 *
	 * @param string|true $url
	 */
	public function host($url, int $isHostIdnaAscii = null, array $refs = []): bool
	{
		return Lib::url()->type_host(null, $url, $isHostIdnaAscii, $refs)->isOk();
	}


	/**
	 * > example.com
	 *
	 * @param string|true $url
	 */
	public function domain($url, int $isHostIdnaAscii = null, array $refs = []): bool
	{
		return Lib::url()->type_domain(null, $url, $isHostIdnaAscii, $refs)->isOk();
	}


	/**
	 * > mysql:host=localhost;dbname=testdb;charset=utf8mb4
	 * > sqlite::memory:
	 */
	public function dsn_pdo($dsn, array $refs = []): bool
	{
		return Lib::url()->type_dsn_pdo(null, $dsn, $refs)->isOk();
	}
}
