<?php

/**
 * This class is autogenerated.
 *
 * @noinspection PhpComposerExtensionStubsInspection
 */

namespace Gzhegow\Lib\Modules\Type\Traits;

use Gzhegow\Lib\Lib;
use Gzhegow\Lib\Modules\Arr\ArrPath;
use Gzhegow\Lib\Modules\Bcmath\Bcnumber;
use Gzhegow\Lib\Modules\Bcmath\Number;
use Gzhegow\Lib\Modules\Net\AddressIpV4;
use Gzhegow\Lib\Modules\Net\AddressIpV6;
use Gzhegow\Lib\Modules\Net\SubnetV4;
use Gzhegow\Lib\Modules\Net\SubnetV6;
use Gzhegow\Lib\Modules\Php\Nil;
use Gzhegow\Lib\Modules\Str\Alphabet;
use Gzhegow\Lib\Modules\Type\Ret;

trait TTrait
{
	/**
	 * > Специальный тип, который значит, что значение можно отбросить или не учитывать, т.к. оно не несёт информации
	 *
	 * @return Ret<string|array|\Countable|null>|string|array|\Countable|null
	 */
	public function blank($fb, $value)
	{
		return Lib::php()->type_blank($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_blank($fb, $value)
	{
		return Lib::php()->type_any_not_blank($fb, $value);
	}


	/**
	 * > Специальный тип, который значит, что значение можно заменить NULL-ом
	 *
	 * @return Ret<mixed>|mixed
	 */
	public function nullable($fb, $value)
	{
		return Lib::php()->type_nullable($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_nullable($fb, $value)
	{
		return Lib::php()->type_any_not_nullable($fb, $value);
	}


	/**
	 * > Специальный тип, который значит, что значение было отправлено пользователем, а не появилось из PHP
	 *
	 * @return Ret<mixed>|mixed
	 */
	public function client($fb, $value)
	{
		return Lib::php()->type_client($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_client($fb, $value)
	{
		return Lib::php()->type_any_not_client($fb, $value);
	}


	/**
	 * > Специальный тип-синоним NULL, переданный пользователем через API, например '{N}'
	 * > в случаях, когда NULL интерпретируется как "не трогать", а NIL как "очистить"
	 *
	 * > NAN не равен ничему даже самому себе
	 * > NIL равен только самому себе
	 * > NULL означает пустоту и им можно заменить значения '', [], `resource (closed)`, NIL, но нельзя заменить NAN
	 *
	 * @return Ret<string|Nil>|string|Nil
	 */
	public function nil($fb, $value)
	{
		return Lib::php()->type_nil($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_nil($fb, $value)
	{
		return Lib::php()->type_any_not_nil($fb, $value);
	}


	/**
	 * @return Ret<null>|null
	 */
	public function null($fb, $value)
	{
		return Lib::php()->type_null($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_null($fb, $value)
	{
		return Lib::php()->type_any_not_null($fb, $value);
	}


	/**
	 * @return Ret<bool>|bool
	 */
	public function php_bool($fb, $value)
	{
		return Lib::php()->type_php_bool($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_php_bool($fb, $value)
	{
		return Lib::php()->type_any_not_php_bool($fb, $value);
	}


	/**
	 * @return Ret<false>|false
	 */
	public function php_bool_false($fb, $value)
	{
		return Lib::php()->type_php_bool_false($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_php_bool_false($fb, $value)
	{
		return Lib::php()->type_any_not_php_bool_false($fb, $value);
	}


	/**
	 * @return Ret<true>|true
	 */
	public function php_bool_true($fb, $value)
	{
		return Lib::php()->type_php_bool_true($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_php_bool_true($fb, $value)
	{
		return Lib::php()->type_any_not_php_bool_true($fb, $value);
	}


	/**
	 * @return Ret<bool>|bool
	 */
	public function bool($fb, $value)
	{
		return Lib::php()->type_bool($fb, $value);
	}


	/**
	 * @return Ret<false>|false
	 */
	public function bool_false($fb, $value)
	{
		return Lib::php()->type_bool_false($fb, $value);
	}


	/**
	 * @return Ret<true>|true
	 */
	public function bool_true($fb, $value)
	{
		return Lib::php()->type_bool_true($fb, $value);
	}


	/**
	 * @return Ret<bool>|bool
	 */
	public function userbool($fb, $value)
	{
		return Lib::php()->type_userbool($fb, $value);
	}


	/**
	 * @return Ret<false>|false
	 */
	public function userbool_false($fb, $value)
	{
		return Lib::php()->type_userbool_false($fb, $value);
	}


	/**
	 * @return Ret<false>|false
	 */
	public function userbool_true($fb, $value)
	{
		return Lib::php()->type_userbool_true($fb, $value);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function array($fb, $value)
	{
		return Lib::php()->type_array($fb, $value);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function array_empty($fb, $value)
	{
		return Lib::php()->type_array_empty($fb, $value);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function array_not_empty($fb, $value)
	{
		return Lib::php()->type_array_not_empty($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_array($fb, $value)
	{
		return Lib::php()->type_any_not_array($fb, $value);
	}


	/**
	 * @return Ret<object>|object
	 */
	public function object($fb, $value)
	{
		return Lib::php()->type_object($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_object($fb, $value)
	{
		return Lib::php()->type_any_not_object($fb, $value);
	}


	/**
	 * @return Ret<\stdClass>|\stdClass
	 */
	public function stdclass($fb, $value)
	{
		return Lib::php()->type_stdclass($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_stdclass($fb, $value)
	{
		return Lib::php()->type_any_not_stdclass($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function php_int($fb, $value)
	{
		return Lib::num()->type_php_int($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function php_float($fb, $value)
	{
		return Lib::num()->type_php_float($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function nan($fb, $value)
	{
		return Lib::num()->type_nan($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_not_nan($fb, $value)
	{
		return Lib::num()->type_float_not_nan($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_maybe_nan($fb, $value)
	{
		return Lib::num()->type_float_maybe_nan($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_nan($fb, $value)
	{
		return Lib::num()->type_any_not_nan($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function finite($fb, $value)
	{
		return Lib::num()->type_finite($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_not_finite($fb, $value)
	{
		return Lib::num()->type_float_not_finite($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_finite($fb, $value)
	{
		return Lib::num()->type_any_not_finite($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function infinite($fb, $value)
	{
		return Lib::num()->type_infinite($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_not_infinite($fb, $value)
	{
		return Lib::num()->type_float_not_infinite($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_infinite($fb, $value)
	{
		return Lib::num()->type_any_not_infinite($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_min($fb, $value)
	{
		return Lib::num()->type_float_min($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_not_float_min($fb, $value)
	{
		return Lib::num()->type_float_not_float_min($fb, $value);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function any_not_float_min($fb, $value)
	{
		return Lib::num()->type_any_not_float_min($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric($fb, $value, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric($fb, $value, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_int($fb, $value, array $refs = [])
	{
		return Lib::num()->type_numeric_int($fb, $value, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_float($fb, $value, array $refs = [])
	{
		return Lib::num()->type_numeric_float($fb, $value, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function decimal($fb, $value, int $scale = 0, array $refs = [])
	{
		return Lib::num()->type_decimal($fb, $value, $scale, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_non_zero($fb, $value, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_non_zero($fb, $value, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_non_negative($fb, $value, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_non_negative($fb, $value, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_non_positive($fb, $value, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_non_positive($fb, $value, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_negative($fb, $value, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_negative($fb, $value, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_positive($fb, $value, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_positive($fb, $value, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_non_negative_or_minus_one($fb, $value, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_non_negative_or_minus_one($fb, $value, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_positive_or_minus_one($fb, $value, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_positive_or_minus_one($fb, $value, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_gt($fb, $value, $gt, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_gt($fb, $value, $gt, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_gte($fb, $value, $gte, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_gte($fb, $value, $gte, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_lt($fb, $value, $lt, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_lt($fb, $value, $lt, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_lte($fb, $value, $lte, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_lte($fb, $value, $lte, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_between($fb, $value, $from, $to, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_between($fb, $value, $from, $to, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function numeric_inside($fb, $value, $from, $to, ?bool $isAllowExp = null, array $refs = [])
	{
		return Lib::num()->type_numeric_inside($fb, $value, $from, $to, $isAllowExp, $refs);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num($fb, $value)
	{
		return Lib::num()->type_num($fb, $value);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int($fb, $value)
	{
		return Lib::num()->type_int($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float($fb, $value)
	{
		return Lib::num()->type_float($fb, $value);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_non_zero($fb, $value)
	{
		return Lib::num()->type_num_non_zero($fb, $value);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_non_negative($fb, $value)
	{
		return Lib::num()->type_num_non_negative($fb, $value);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_non_positive($fb, $value)
	{
		return Lib::num()->type_num_non_positive($fb, $value);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_negative($fb, $value)
	{
		return Lib::num()->type_num_negative($fb, $value);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_positive($fb, $value)
	{
		return Lib::num()->type_num_positive($fb, $value);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_non_negative_or_minus_one($fb, $value)
	{
		return Lib::num()->type_num_non_negative_or_minus_one($fb, $value);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_positive_or_minus_one($fb, $value)
	{
		return Lib::num()->type_num_positive_or_minus_one($fb, $value);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_gt($fb, $value, $gt)
	{
		return Lib::num()->type_num_gt($fb, $value, $gt);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_gte($fb, $value, $gte)
	{
		return Lib::num()->type_num_gte($fb, $value, $gte);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_lt($fb, $value, $lt)
	{
		return Lib::num()->type_num_lt($fb, $value, $lt);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_lte($fb, $value, $lte)
	{
		return Lib::num()->type_num_lte($fb, $value, $lte);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_between($fb, $value, $from, $to)
	{
		return Lib::num()->type_num_between($fb, $value, $from, $to);
	}


	/**
	 * @return Ret<int|float>|int|float
	 */
	public function num_inside($fb, $value, $from, $to)
	{
		return Lib::num()->type_num_inside($fb, $value, $from, $to);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_non_zero($fb, $value)
	{
		return Lib::num()->type_int_non_zero($fb, $value);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_non_negative($fb, $value)
	{
		return Lib::num()->type_int_non_negative($fb, $value);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_non_positive($fb, $value)
	{
		return Lib::num()->type_int_non_positive($fb, $value);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_negative($fb, $value)
	{
		return Lib::num()->type_int_negative($fb, $value);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_positive($fb, $value)
	{
		return Lib::num()->type_int_positive($fb, $value);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_non_negative_or_minus_one($fb, $value)
	{
		return Lib::num()->type_int_non_negative_or_minus_one($fb, $value);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_positive_or_minus_one($fb, $value)
	{
		return Lib::num()->type_int_positive_or_minus_one($fb, $value);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_gt($fb, $value, $gt)
	{
		return Lib::num()->type_int_gt($fb, $value, $gt);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_gte($fb, $value, $gte)
	{
		return Lib::num()->type_int_gte($fb, $value, $gte);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_lt($fb, $value, $lt)
	{
		return Lib::num()->type_int_lt($fb, $value, $lt);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_lte($fb, $value, $lte)
	{
		return Lib::num()->type_int_lte($fb, $value, $lte);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_between($fb, $value, $from, $to)
	{
		return Lib::num()->type_int_between($fb, $value, $from, $to);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function int_inside($fb, $value, $from, $to)
	{
		return Lib::num()->type_int_inside($fb, $value, $from, $to);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_non_zero($fb, $value)
	{
		return Lib::num()->type_float_non_zero($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_non_negative($fb, $value)
	{
		return Lib::num()->type_float_non_negative($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_non_positive($fb, $value)
	{
		return Lib::num()->type_float_non_positive($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_negative($fb, $value)
	{
		return Lib::num()->type_float_negative($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_positive($fb, $value)
	{
		return Lib::num()->type_float_positive($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_non_negative_or_minus_one($fb, $value)
	{
		return Lib::num()->type_float_non_negative_or_minus_one($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_positive_or_minus_one($fb, $value)
	{
		return Lib::num()->type_float_positive_or_minus_one($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_gt($fb, $value, $gt)
	{
		return Lib::num()->type_float_gt($fb, $value, $gt);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_gte($fb, $value, $gte)
	{
		return Lib::num()->type_float_gte($fb, $value, $gte);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_lt($fb, $value, $lt)
	{
		return Lib::num()->type_float_lt($fb, $value, $lt);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_lte($fb, $value, $lte)
	{
		return Lib::num()->type_float_lte($fb, $value, $lte);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_between($fb, $value, $from, $to)
	{
		return Lib::num()->type_float_between($fb, $value, $from, $to);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function float_inside($fb, $value, $from, $to)
	{
		return Lib::num()->type_float_inside($fb, $value, $from, $to);
	}


	/**
	 * @return Ret<Number>|Number
	 */
	public function number($fb, $value, ?bool $isAllowExp = null)
	{
		return Lib::num()->type_number($fb, $value, $isAllowExp);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function exponent($fb, $value)
	{
		return Lib::num()->type_exponent($fb, $value);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function scale($fb, $value)
	{
		return Lib::num()->type_scale($fb, $value);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function percent($fb, $value)
	{
		return Lib::num()->type_percent($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function percent_numeric($fb, $value)
	{
		return Lib::num()->type_percent_numeric($fb, $value);
	}


	/**
	 * @return Ret<float>|float
	 */
	public function ratio($fb, $value)
	{
		return Lib::num()->type_ratio($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function ratio_numeric($fb, $value)
	{
		return Lib::num()->type_ratio_numeric($fb, $value);
	}


	/**
	 * @return Ret<Bcnumber>|Bcnumber
	 */
	public function bcnumber($fb, $value)
	{
		return Lib::bcmath()->type_bcnumber($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function php_string($fb, $value)
	{
		return Lib::str()->type_php_string($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function php_string_empty($fb, $value)
	{
		return Lib::str()->type_php_string_empty($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function php_string_not_empty($fb, $value)
	{
		return Lib::str()->type_php_string_not_empty($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function php_trim($fb, $value)
	{
		return Lib::str()->type_php_trim($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function string($fb, $value)
	{
		return Lib::str()->type_string($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function string_empty($fb, $value)
	{
		return Lib::str()->type_string_empty($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function string_not_empty($fb, $value)
	{
		return Lib::str()->type_string_not_empty($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function trim($fb, $value, ?string $characters = null)
	{
		return Lib::str()->type_trim($fb, $value, $characters);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function char($fb, $value)
	{
		return Lib::str()->type_char($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function letter($fb, $value)
	{
		return Lib::str()->type_letter($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function word($fb, $value)
	{
		return Lib::str()->type_word($fb, $value);
	}


	/**
	 * @return Ret<Alphabet>|Alphabet
	 */
	public function alphabet($fb, $value)
	{
		return Lib::str()->type_alphabet($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function ctype_digit($fb, $value)
	{
		return Lib::str()->type_ctype_digit($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function ctype_alpha($fb, $value, ?bool $allowUpperCase = null)
	{
		return Lib::str()->type_ctype_alpha($fb, $value, $allowUpperCase);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function ctype_alnum($fb, $value, ?bool $allowUpperCase = null)
	{
		return Lib::str()->type_ctype_alnum($fb, $value, $allowUpperCase);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function base($fb, $value, $alphabet)
	{
		return Lib::crypt()->type_base($fb, $value, $alphabet);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function base_bin($fb, $value)
	{
		return Lib::crypt()->type_base_bin($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function base_oct($fb, $value)
	{
		return Lib::crypt()->type_base_oct($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function base_dec($fb, $value)
	{
		return Lib::crypt()->type_base_dec($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function base_hex($fb, $value)
	{
		return Lib::crypt()->type_base_hex($fb, $value);
	}


	/**
	 * @return Ret<int|string>|int|string
	 */
	public function key($fb, $key)
	{
		return Lib::arr()->type_key($fb, $key);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function key_exists($fb, array $array, $key)
	{
		return Lib::arr()->type_key_exists($fb, $array, $key);
	}


	/**
	 * @return Ret<mixed>|mixed
	 */
	public function value_in_array($fb, array $array, $key, ?bool $strict = null)
	{
		return Lib::arr()->type_value_in_array($fb, $array, $key, $strict);
	}


	/**
	 * @return Ret<int|string>|int|string
	 */
	public function value_in_array_key($fb, array $array, $key, ?bool $strict = null)
	{
		return Lib::arr()->type_value_in_array_key($fb, $array, $key, $strict);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function value_in_array_pos($fb, array $array, $key, ?bool $strict = null)
	{
		return Lib::arr()->type_value_in_array_pos($fb, $array, $key, $strict);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function keys_exists($fb, array $array, $keys)
	{
		return Lib::arr()->type_keys_exists($fb, $array, $keys);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function keys_not_exists($fb, array $array, $keys)
	{
		return Lib::arr()->type_keys_not_exists($fb, $array, $keys);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function values_in_array($fb, array $array, $keys, ?bool $strict = null)
	{
		return Lib::arr()->type_values_in_array($fb, $array, $keys, $strict);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function values_not_in_array($fb, array $array, $keys, ?bool $strict = null)
	{
		return Lib::arr()->type_values_not_in_array($fb, $array, $keys, $strict);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function array_plain($fb, $value, ?int $maxDepth = null)
	{
		return Lib::arr()->type_array_plain($fb, $value, $maxDepth);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function list($fb, $value, ?int $plainMaxDepth = null)
	{
		return Lib::arr()->type_list($fb, $value, $plainMaxDepth);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function list_sorted($fb, $value, ?int $plainMaxDepth = null)
	{
		return Lib::arr()->type_list_sorted($fb, $value, $plainMaxDepth);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function dict($fb, $value, ?int $plainMaxDepth = null)
	{
		return Lib::arr()->type_dict($fb, $value, $plainMaxDepth);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function dict_sorted($fb, $value, ?int $plainMaxDepth = null, $fnSortCmp = null)
	{
		return Lib::arr()->type_dict_sorted($fb, $value, $plainMaxDepth, $fnSortCmp);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function table($fb, $value)
	{
		return Lib::arr()->type_table($fb, $value);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function matrix($fb, $value)
	{
		return Lib::arr()->type_matrix($fb, $value);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function matrix_sorted($fb, $value)
	{
		return Lib::arr()->type_matrix_sorted($fb, $value);
	}


	/**
	 * @return Ret<ArrPath>|ArrPath
	 */
	public function arrpath($fb, $path)
	{
		return Lib::arr()->type_arrpath($fb, $path);
	}


	/**
	 * @return Ret<ArrPath>|ArrPath
	 */
	public function arrpath_dot($fb, $path, ?string $dot = '.')
	{
		return Lib::arr()->type_arrpath_dot($fb, $path, $dot);
	}


	/**
	 * @return Ret<array>|array
	 */
	public function array_of_type($fb, $value, string $type)
	{
		return Lib::arr()->type_array_of_type($fb, $value, $type);
	}


	/**
	 * @return Ret<resource[]>|resource[]
	 */
	public function array_of_resource_type($fb, $value, string $resourceType)
	{
		return Lib::arr()->type_array_of_resource_type($fb, $value, $resourceType);
	}


	/**
	 * @template T
	 *
	 * @param class-string<T> $className
	 *
	 * @return Ret<T[]>|T[]
	 */
	public function array_of_a($fb, $value, string $className)
	{
		return Lib::arr()->type_array_of_a($fb, $value, $className);
	}


	/**
	 * @template T
	 *
	 * @param class-string<T> $className
	 *
	 * @return Ret<T[]>|T[]
	 */
	public function array_of_class($fb, $value, string $className)
	{
		return Lib::arr()->type_array_of_class($fb, $value, $className);
	}


	/**
	 * @template T
	 *
	 * @param class-string<T> $className
	 *
	 * @return Ret<T[]>|T[]
	 */
	public function array_of_subclass($fb, $value, string $className)
	{
		return Lib::arr()->type_array_of_subclass($fb, $value, $className);
	}


	/**
	 * @param callable $fn
	 *
	 * @return Ret<array>|array
	 *
	 * @noinspection PhpDocSignatureIsNotCompleteInspection
	 */
	public function array_of_callback($fb, $value, callable $fn, array $args = [])
	{
		return Lib::arr()->type_array_of_callback($fb, $value, $fn, $args);
	}


	/**
	 * @return Ret<array{ 0: string, 1: int }>|array{ 0: string, 1: int }
	 */
	public function file_line($fb, $value)
	{
		return Lib::debug()->type_file_line($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function html_tag($fb, $value)
	{
		return Lib::format()->type_html_tag($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function xml_tag($fb, $value)
	{
		return Lib::format()->type_xml_tag($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function xml_nstag($fb, $value)
	{
		return Lib::format()->type_xml_nstag($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function regex($fb, $value)
	{
		return Lib::preg()->type_regex($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function regexp($fb, $value)
	{
		return Lib::preg()->type_regexp($fb, $value);
	}


	/**
	 * @return Ret<AddressIpV4|AddressIpV6>|AddressIpV4|AddressIpV6
	 */
	public function address_ip($fb, $value)
	{
		return Lib::net()->type_address_ip($fb, $value);
	}


	/**
	 * @return Ret<AddressIpV4>|AddressIpV4
	 */
	public function address_ip_v4($fb, $value)
	{
		return Lib::net()->type_address_ip_v4($fb, $value);
	}


	/**
	 * @return Ret<AddressIpV6>|AddressIpV6
	 */
	public function address_ip_v6($fb, $value)
	{
		return Lib::net()->type_address_ip_v6($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function address_mac($fb, $value)
	{
		return Lib::net()->type_address_mac($fb, $value);
	}


	/**
	 * @return Ret<SubnetV4|SubnetV6>|SubnetV4|SubnetV6
	 */
	public function subnet($fb, $value, ?string $ipFallback = null)
	{
		return Lib::net()->type_subnet($fb, $value, $ipFallback);
	}


	/**
	 * @return Ret<SubnetV4>|SubnetV4
	 */
	public function subnet_v4($fb, $value, ?string $ipFallback = null)
	{
		return Lib::net()->type_subnet_v4($fb, $value, $ipFallback);
	}


	/**
	 * @return Ret<SubnetV6>|SubnetV6
	 */
	public function subnet_v6($fb, $value, ?string $ipFallback = null)
	{
		return Lib::net()->type_subnet_v6($fb, $value, $ipFallback);
	}


	/**
	 * @param string|true             $value
	 * @param string|false|array|null $query
	 * @param string|false|null       $fragment
	 *
	 * @return Ret<string>|string
	 */
	public function url(
		$fb,
		$value,
		$query = null,
		$fragment = null,
		?int $isHostIdnaAscii = null,
		?int $isLinkUrlencoded = null,
		array $refs = []
	) {
		return Lib::url()->type_url($fb, $value, $query, $fragment, $isHostIdnaAscii, $isLinkUrlencoded, $refs);
	}


	/**
	 * @param string|true             $value
	 * @param string|false|array|null $query
	 * @param string|false|null       $fragment
	 *
	 * @return Ret<string>|string
	 */
	public function uri(
		$fb,
		$value,
		$query = null,
		$fragment = null,
		?int $isHostIdnaAscii = null,
		?int $isLinkUrlencoded = null,
		array $refs = []
	) {
		return Lib::url()->type_uri($fb, $value, $query, $fragment, $isHostIdnaAscii, $isLinkUrlencoded, $refs);
	}


	/**
	 * @param string|true $value
	 *
	 * @return Ret<string>|string
	 */
	public function host($fb, $value, ?int $isHostIdnaAscii = null, array $refs = [])
	{
		return Lib::url()->type_host($fb, $value, $isHostIdnaAscii, $refs);
	}


	/**
	 * @param string|true $value
	 *
	 * @return Ret<string>|string
	 */
	public function domain($fb, $value, ?int $isHostIdnaAscii = null, array $refs = [])
	{
		return Lib::url()->type_domain($fb, $value, $isHostIdnaAscii, $refs);
	}


	/**
	 * @param string|true             $value
	 * @param string|false|array|null $query
	 * @param string|false|null       $fragment
	 *
	 * @return Ret<string>|string
	 */
	public function link($fb, $value, $query = null, $fragment = null, ?int $isLinkUrlencoded = null, array $refs = [])
	{
		return Lib::url()->type_link($fb, $value, $query, $fragment, $isLinkUrlencoded, $refs);
	}


	/**
	 * @param string $value
	 *
	 * @return Ret<string>|string
	 */
	public function dsn_pdo($fb, $value, array $refs = [])
	{
		return Lib::url()->type_dsn_pdo($fb, $value, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function uuid($fb, $value)
	{
		return Lib::random()->type_uuid($fb, $value);
	}


	/**
	 * @return Ret<array|\Countable>|array|\Countable
	 */
	public function countable($fb, $value)
	{
		return Lib::php()->type_countable($fb, $value);
	}


	/**
	 * @return Ret<\Countable>|\Countable
	 */
	public function countable_object($fb, $value)
	{
		return Lib::php()->type_countable_object($fb, $value);
	}


	/**
	 * @return Ret<array|\Countable>|array|\Countable
	 */
	public function sizeable($fb, $value)
	{
		return Lib::php()->type_sizeable($fb, $value);
	}


	/**
	 * @return Ret<\DateTimeZone>|\DateTimeZone
	 */
	public function timezone($fb, $timezone, ?array $allowedTimezoneTypes = null)
	{
		return Lib::date()->type_timezone($fb, $timezone, $allowedTimezoneTypes);
	}


	/**
	 * @return Ret<\DateTimeZone>|\DateTimeZone
	 */
	public function timezone_offset($fb, $timezoneOrOffset)
	{
		return Lib::date()->type_timezone_offset($fb, $timezoneOrOffset);
	}


	/**
	 * @return Ret<\DateTimeZone>|\DateTimeZone
	 */
	public function timezone_abbr($fb, $timezoneOrAbbr)
	{
		return Lib::date()->type_timezone_abbr($fb, $timezoneOrAbbr);
	}


	/**
	 * @return Ret<\DateTimeZone>|\DateTimeZone
	 */
	public function timezone_name($fb, $timezoneOrName)
	{
		return Lib::date()->type_timezone_name($fb, $timezoneOrName);
	}


	/**
	 * @return Ret<\DateTimeZone>|\DateTimeZone
	 */
	public function timezone_nameabbr($fb, $timezoneOrNameOrAbbr)
	{
		return Lib::date()->type_timezone_nameabbr($fb, $timezoneOrNameOrAbbr);
	}


	/**
	 * @return Ret<\DateTimeInterface>|\DateTimeInterface
	 */
	public function date($fb, $datestring, $timezoneFallback = null)
	{
		return Lib::date()->type_date($fb, $datestring, $timezoneFallback);
	}


	/**
	 * @return Ret<\DateTime>|\DateTime
	 */
	public function adate($fb, $datestring, $timezoneFallback = null)
	{
		return Lib::date()->type_adate($fb, $datestring, $timezoneFallback);
	}


	/**
	 * @return Ret<\DateTimeImmutable>|\DateTimeImmutable
	 */
	public function idate($fb, $datestring, $timezoneFallback = null)
	{
		return Lib::date()->type_idate($fb, $datestring, $timezoneFallback);
	}


	/**
	 * @return Ret<\DateTimeInterface>|\DateTimeInterface
	 */
	public function date_formatted($fb, $dateFormatted, $formats, $timezoneFallback = null)
	{
		return Lib::date()->type_date_formatted($fb, $dateFormatted, $formats, $timezoneFallback);
	}


	/**
	 * @return Ret<\DateTime>|\DateTime
	 */
	public function adate_formatted($fb, $dateFormatted, $formats, $timezoneFallback = null)
	{
		return Lib::date()->type_adate_formatted($fb, $dateFormatted, $formats, $timezoneFallback);
	}


	/**
	 * @return Ret<\DateTimeImmutable>|\DateTimeImmutable
	 */
	public function idate_formatted($fb, $dateFormatted, $formats, $timezoneFallback = null)
	{
		return Lib::date()->type_idate_formatted($fb, $dateFormatted, $formats, $timezoneFallback);
	}


	/**
	 * @return Ret<\DateTimeInterface>|\DateTimeInterface
	 */
	public function date_tz($fb, $datestring, ?array $allowedTimezoneTypes = null)
	{
		return Lib::date()->type_date_tz($fb, $datestring, $allowedTimezoneTypes);
	}


	/**
	 * @return Ret<\DateTime>|\DateTime
	 */
	public function adate_tz($fb, $datestring, ?array $allowedTimezoneTypes = null)
	{
		return Lib::date()->type_adate_tz($fb, $datestring, $allowedTimezoneTypes);
	}


	/**
	 * @return Ret<\DateTimeImmutable>|\DateTimeImmutable
	 */
	public function idate_tz($fb, $datestring, ?array $allowedTimezoneTypes = null)
	{
		return Lib::date()->type_idate_tz($fb, $datestring, $allowedTimezoneTypes);
	}


	/**
	 * @return Ret<\DateTimeInterface>|\DateTimeInterface
	 */
	public function date_tz_formatted($fb, $dateFormatted, $formats, ?array $allowedTimezoneTypes = null)
	{
		return Lib::date()->type_date_tz_formatted($fb, $dateFormatted, $formats, $allowedTimezoneTypes);
	}


	/**
	 * @return Ret<\DateTime>|\DateTime
	 */
	public function adate_tz_formatted($fb, $dateFormatted, $formats, ?array $allowedTimezoneTypes = null)
	{
		return Lib::date()->type_adate_tz_formatted($fb, $dateFormatted, $formats, $allowedTimezoneTypes);
	}


	/**
	 * @return Ret<\DateTimeImmutable>|\DateTimeImmutable
	 */
	public function idate_tz_formatted($fb, $dateFormatted, $formats, ?array $allowedTimezoneTypes = null)
	{
		return Lib::date()->type_idate_tz_formatted($fb, $dateFormatted, $formats, $allowedTimezoneTypes);
	}


	/**
	 * @return Ret<\DateTimeInterface>|\DateTimeInterface
	 */
	public function date_no_tz($fb, $datestring, $timezoneFallback = null)
	{
		return Lib::date()->type_date_no_tz($fb, $datestring, $timezoneFallback);
	}


	/**
	 * @return Ret<\DateTime>|\DateTime
	 */
	public function adate_no_tz($fb, $datestring, $timezoneFallback = null)
	{
		return Lib::date()->type_adate_no_tz($fb, $datestring, $timezoneFallback);
	}


	/**
	 * @return Ret<\DateTimeImmutable>|\DateTimeImmutable
	 */
	public function idate_no_tz($fb, $datestring, $timezoneFallback = null)
	{
		return Lib::date()->type_idate_no_tz($fb, $datestring, $timezoneFallback);
	}


	/**
	 * @return Ret<\DateTimeInterface>|\DateTimeInterface
	 */
	public function date_no_tz_formatted($fb, $dateFormatted, $formats, $timezoneFallback = null)
	{
		return Lib::date()->type_date_no_tz_formatted($fb, $dateFormatted, $formats, $timezoneFallback);
	}


	/**
	 * @return Ret<\DateTime>|\DateTime
	 */
	public function adate_no_tz_formatted($fb, $dateFormatted, $formats, $timezoneFallback = null)
	{
		return Lib::date()->type_adate_no_tz_formatted($fb, $dateFormatted, $formats, $timezoneFallback);
	}


	/**
	 * @return Ret<\DateTimeImmutable>|\DateTimeImmutable
	 */
	public function idate_no_tz_formatted($fb, $dateFormatted, $formats, $timezoneFallback = null)
	{
		return Lib::date()->type_idate_no_tz_formatted($fb, $dateFormatted, $formats, $timezoneFallback);
	}


	/**
	 * @return Ret<\DateTimeInterface>|\DateTimeInterface
	 */
	public function date_microtime($fb, $microtime, $timezoneSet = null)
	{
		return Lib::date()->type_date_microtime($fb, $microtime, $timezoneSet);
	}


	/**
	 * @return Ret<\DateTime>|\DateTime
	 */
	public function adate_microtime($fb, $microtime, $timezoneSet = null)
	{
		return Lib::date()->type_adate_microtime($fb, $microtime, $timezoneSet);
	}


	/**
	 * @return Ret<\DateTimeImmutable>|\DateTimeImmutable
	 */
	public function idate_microtime($fb, $microtime, $timezoneSet = null)
	{
		return Lib::date()->type_idate_microtime($fb, $microtime, $timezoneSet);
	}


	/**
	 * @return Ret<\DateInterval>|\DateInterval
	 */
	public function interval($fb, $interval)
	{
		return Lib::date()->type_interval($fb, $interval);
	}


	/**
	 * @return Ret<\DateInterval>|\DateInterval
	 */
	public function interval_duration($fb, $duration)
	{
		return Lib::date()->type_interval_duration($fb, $duration);
	}


	/**
	 * @return Ret<\DateInterval>|\DateInterval
	 */
	public function interval_datestring($fb, $datestring)
	{
		return Lib::date()->type_interval_datestring($fb, $datestring);
	}


	/**
	 * @return Ret<\DateInterval>|\DateInterval
	 */
	public function interval_microtime($fb, $microtime)
	{
		return Lib::date()->type_interval_microtime($fb, $microtime);
	}


	/**
	 * @return Ret<\DateInterval>|\DateInterval
	 */
	public function interval_ago($fb, $date, ?\DateTimeInterface $from = null, ?bool $reverse = null)
	{
		return Lib::date()->type_interval_ago($fb, $date, $from, $reverse);
	}


	/**
	 * @template-covariant T of object
	 *
	 * @param class-string<T>|T|mixed $value
	 *
	 * @return Ret<class-string<T>>|class-string<T>
	 */
	public function struct_exists($fb, $value, ?int $flags = null)
	{
		return Lib::php()->type_struct_exists($fb, $value, $flags);
	}


	/**
	 * @template-covariant T of object
	 *
	 * @param class-string<T>|T|mixed $value
	 *
	 * @return Ret<class-string<T>>|class-string<T>
	 */
	public function struct($fb, $value, ?int $flags = null)
	{
		return Lib::php()->type_struct($fb, $value, $flags);
	}


	/**
	 * @template-covariant T of object
	 *
	 * @param class-string<T>|T|mixed $value
	 *
	 * @return Ret<class-string<T>>|class-string<T>
	 */
	public function struct_class($fb, $value, ?int $flags = null)
	{
		return Lib::php()->type_struct_class($fb, $value, $flags);
	}


	/**
	 * @return Ret<class-string>|class-string
	 */
	public function struct_interface($fb, $value, ?int $flags = null)
	{
		return Lib::php()->type_struct_interface($fb, $value, $flags);
	}


	/**
	 * @return Ret<class-string>|class-string
	 */
	public function struct_trait($fb, $value, ?int $flags = null)
	{
		return Lib::php()->type_struct_trait($fb, $value, $flags);
	}


	/**
	 * @template-covariant T of \UnitEnum
	 *
	 * @param class-string<T>|T|mixed $value
	 *
	 * @return Ret<class-string<T>>|class-string<T>
	 */
	public function struct_enum($fb, $value, ?int $flags = null)
	{
		return Lib::php()->type_struct_enum($fb, $value, $flags);
	}


	/**
	 * @template-covariant T of object
	 *
	 * @param class-string<T>|T|mixed $value
	 *
	 * @return Ret<class-string<T>>|class-string<T>
	 */
	public function struct_fqcn($fb, $value, ?int $flags = null)
	{
		return Lib::php()->type_struct_fqcn($fb, $value, $flags);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function struct_namespace($fb, $value, ?int $flags = null)
	{
		return Lib::php()->type_struct_namespace($fb, $value, $flags);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function struct_basename($fb, $value, ?int $flags = null)
	{
		return Lib::php()->type_struct_basename($fb, $value, $flags);
	}


	/**
	 * @return Ret<resource>|resource
	 */
	public function resource($fb, $value, ?string $resourceType = null)
	{
		return Lib::php()->type_resource($fb, $value, $resourceType);
	}


	/**
	 * @return Ret<resource>|resource
	 */
	public function resource_opened($fb, $value, ?string $resourceType = null)
	{
		return Lib::php()->type_resource_opened($fb, $value, $resourceType);
	}


	/**
	 * @return Ret<resource>|resource
	 */
	public function resource_closed($fb, $value)
	{
		return Lib::php()->type_resource_closed($fb, $value);
	}


	/**
	 * @return Ret<resource>|resource
	 */
	public function any_not_resource($fb, $value)
	{
		return Lib::php()->type_any_not_resource($fb, $value);
	}


	/**
	 * @return Ret<resource|\CurlHandle>|resource|\CurlHandle
	 */
	public function curl($fb, $value)
	{
		return Lib::php()->type_curl($fb, $value);
	}


	/**
	 * @template-covariant T of \UnitEnum
	 *
	 * @param T|int|string         $value
	 * @param class-string<T>|null $enumClass
	 *
	 * @return Ret<T>|T
	 */
	public function enum_case($fb, $value, ?string $enumClass = null)
	{
		return Lib::php()->type_enum_case($fb, $value, $enumClass);
	}


	/**
	 * > метод не всегда callable, поскольку строка 'class->method' не является callable
	 * > метод не всегда callable, поскольку массив [ 'class', 'method' ] не является callable, если метод публичный
	 * > используйте type_callable_string, если собираетесь вызывать метод
	 * > используйте type_callable_array, если собираетесь вызывать метод
	 *
	 * @param array{ 0?: array{ 0: class-string, 1: string }, 1?: string } $refs
	 *
	 * @return Ret<bool>|bool
	 */
	public function method($fb, $value, array $refs = [])
	{
		return Lib::php()->type_method($fb, $value, $refs);
	}


	/**
	 * @return Ret<array{ 0: class-string, 1: string }>|array{ 0: class-string, 1: string }
	 */
	public function method_array($fb, $value)
	{
		return Lib::php()->type_method_array($fb, $value);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function method_string($fb, $value)
	{
		return Lib::php()->type_method_string($fb, $value);
	}


	/**
	 * @param string|object $newScope
	 *
	 * @return Ret<callable>|callable
	 */
	public function callable($fb, $value, $newScope = 'static')
	{
		return Lib::php()->type_callable($fb, $value, $newScope);
	}


	/**
	 * @return Ret<callable|\Closure|object>|callable|\Closure|object
	 */
	public function callable_object($fb, $value, $newScope = 'static')
	{
		return Lib::php()->type_callable_object($fb, $value, $newScope);
	}


	/**
	 * @return Ret<\Closure>|\Closure
	 */
	public function callable_object_closure($fb, $value, $newScope = 'static')
	{
		return Lib::php()->type_callable_object_closure($fb, $value, $newScope);
	}


	/**
	 * @return Ret<callable|object>|callable|object
	 */
	public function callable_object_invokable($fb, $value, $newScope = 'static')
	{
		return Lib::php()->type_callable_object_invokable($fb, $value, $newScope);
	}


	/**
	 * @param string|object $newScope
	 *
	 * @return Ret<callable|array{ 0: object|class-string, 1: string }>|callable|array{ 0: object|class-string, 1: string }
	 */
	public function callable_array($fb, $value, $newScope = 'static')
	{
		return Lib::php()->type_callable_array($fb, $value, $newScope);
	}


	/**
	 * @param string|object $newScope
	 *
	 * @return Ret<callable|array{ 0: object|class-string, 1: string }>|callable|array{ 0: object|class-string, 1: string }
	 */
	public function callable_array_method($fb, $value, $newScope = 'static')
	{
		return Lib::php()->type_callable_array_method($fb, $value, $newScope);
	}


	/**
	 * @param string|object $newScope
	 *
	 * @return Ret<callable|array{ 0: class-string, 1: string }>|callable|array{ 0: class-string, 1: string }
	 */
	public function callable_array_method_static($fb, $value, $newScope = 'static')
	{
		return Lib::php()->type_callable_array_method_static($fb, $value, $newScope);
	}


	/**
	 * @param string|object $newScope
	 *
	 * @return Ret<callable|array{ 0: object, 1: string }>|callable|array{ 0: object, 1: string }
	 */
	public function callable_array_method_non_static($fb, $value, $newScope = 'static')
	{
		return Lib::php()->type_callable_array_method_non_static($fb, $value, $newScope);
	}


	/**
	 * @return Ret<callable|string>|callable|string
	 */
	public function callable_string($fb, $value, $newScope = 'static')
	{
		return Lib::php()->type_callable_string($fb, $value, $newScope);
	}


	/**
	 * @return Ret<callable|string>|callable|string
	 */
	public function callable_string_function($fb, $value)
	{
		return Lib::php()->type_callable_string_function($fb, $value);
	}


	/**
	 * @return Ret<callable|string>|callable|string
	 */
	public function callable_string_function_internal($fb, $value)
	{
		return Lib::php()->type_callable_string_function_internal($fb, $value);
	}


	/**
	 * @return Ret<callable|string>|callable|string
	 */
	public function callable_string_function_non_internal($fb, $value)
	{
		return Lib::php()->type_callable_string_function_non_internal($fb, $value);
	}


	/**
	 * @return Ret<callable|string>|callable|string
	 */
	public function callable_string_method_static($fb, $value, $newScope = 'static')
	{
		return Lib::php()->type_callable_string_method_static($fb, $value, $newScope);
	}


	/**
	 * @param array{ 0: array|null } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function path($fb, $value, array $refs = [])
	{
		return Lib::php()->type_path($fb, $value, $refs);
	}


	/**
	 * @param array{ 0: array|null } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function path_normalized($fb, $value, ?string $separator = null, array $refs = [])
	{
		return Lib::php()->type_path_normalized($fb, $value, $separator, $refs);
	}


	/**
	 * @return Ret<true>|true
	 */
	public function is_os_windows($fb)
	{
		return Lib::php()->type_is_os_windows($fb);
	}


	/**
	 * @return Ret<true>|true
	 */
	public function is_sapi_terminal($fb)
	{
		return Lib::php()->type_is_sapi_terminal($fb);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function is_extension_loaded($fb, $extension)
	{
		return Lib::php()->type_is_extension_loaded($fb, $extension);
	}


	/**
	 * @return Ret<int>|int
	 */
	public function chmod($fb, $value)
	{
		return Lib::fs()->type_chmod($fb, $value);
	}


	/**
	 * @param array{ 0: array|null } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function realpath($fb, $value, ?bool $isAllowSymlink = null, array $refs = [])
	{
		return Lib::fs()->type_realpath($fb, $value, $isAllowSymlink, $refs);
	}


	/**
	 * @param array{ 0: array|null } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function freepath($fb, $value, array $refs = [])
	{
		return Lib::fs()->type_freepath($fb, $value, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function freepath_normalized($fb, $value, ?string $separator = null, array $refs = [])
	{
		return Lib::fs()->type_freepath_normalized($fb, $value, $separator, $refs);
	}


	/**
	 * @param array{ 0: array|null } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function dirpath($fb, $value, ?bool $isAllowExists, ?bool $isAllowSymlink = null, array $refs = [])
	{
		return Lib::fs()->type_dirpath($fb, $value, $isAllowExists, $isAllowSymlink, $refs);
	}


	/**
	 * @param array{ 0: array|null } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function filepath($fb, $value, ?bool $isAllowExists, ?bool $isAllowSymlink = null, array $refs = [])
	{
		return Lib::fs()->type_filepath($fb, $value, $isAllowExists, $isAllowSymlink, $refs);
	}


	/**
	 * @param array{ 0: array|null } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function dirpath_realpath($fb, $value, ?bool $isAllowSymlink = null, array $refs = [])
	{
		return Lib::fs()->type_dirpath_realpath($fb, $value, $isAllowSymlink, $refs);
	}


	/**
	 * @param array{ 0: array|null } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function filepath_realpath($fb, $value, ?bool $isAllowSymlink = null, array $refs = [])
	{
		return Lib::fs()->type_filepath_realpath($fb, $value, $isAllowSymlink, $refs);
	}


	/**
	 * @return Ret<string>|string
	 */
	public function filename($fb, $value)
	{
		return Lib::fs()->type_filename($fb, $value);
	}


	/**
	 * @return Ret<\SplFileInfo>|\SplFileInfo
	 */
	public function file(
		$fb,
		$value,
		?array $extensions = null,
		?array $mimeTypes = null,
		?array $filters = null,
		array $refs = []
	) {
		return Lib::fs()->type_file($fb, $value, $extensions, $mimeTypes, $filters, $refs);
	}


	/**
	 * @return Ret<\SplFileInfo>|\SplFileInfo
	 */
	public function image(
		$fb,
		$value,
		?array $extensions = null,
		?array $mimeTypes = null,
		?array $filters = null,
		array $refs = []
	) {
		return Lib::fs()->type_image($fb, $value, $extensions, $mimeTypes, $filters, $refs);
	}


	/**
	 * @return Ret<resource|\Socket>|resource|\Socket
	 */
	public function socket($fb, $value)
	{
		return Lib::fs()->type_socket($fb, $value);
	}


	/**
	 * @return Ret<resource>|resource
	 */
	public function stream($fb, $value)
	{
		return Lib::fs()->type_stream($fb, $value);
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function email($fb, $value, ?array $filters = null, array $refs = [])
	{
		return Lib::social()->type_email($fb, $value, $filters, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function email_fake($fb, $value, array $refs = [])
	{
		return Lib::social()->type_email_fake($fb, $value, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function email_non_fake($fb, $value, ?array $filters = null, array $refs = [])
	{
		return Lib::social()->type_email_non_fake($fb, $value, $filters, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function email_maybe_fake($fb, $value, ?array $filters = null, array $refs = [])
	{
		return Lib::social()->type_email_maybe_fake($fb, $value, $filters, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function phone($fb, $value, array $refs = [])
	{
		return Lib::social()->type_phone($fb, $value, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function phone_fake($fb, $value, array $refs = [])
	{
		return Lib::social()->type_phone_fake($fb, $value, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function phone_non_fake($fb, $value, array $refs = [])
	{
		return Lib::social()->type_phone_non_fake($fb, $value, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function phone_maybe_fake($fb, $value, array $refs = [])
	{
		return Lib::social()->type_phone_maybe_fake($fb, $value, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string, 3?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function phone_real($fb, $value, ?string $region = '', array $refs = [])
	{
		return Lib::social()->type_phone_real($fb, $value, $region, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function tel($fb, $value, array $refs = [])
	{
		return Lib::social()->type_tel($fb, $value, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function tel_fake($fb, $value, array $refs = [])
	{
		return Lib::social()->type_tel_fake($fb, $value, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function tel_non_fake($fb, $value, array $refs = [])
	{
		return Lib::social()->type_tel_non_fake($fb, $value, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function tel_maybe_fake($fb, $value, array $refs = [])
	{
		return Lib::social()->type_tel_maybe_fake($fb, $value, $refs);
	}


	/**
	 * @param array{ 0?: string, 1?: string, 2?: string } $refs
	 *
	 * @return Ret<string>|string
	 */
	public function tel_real($fb, $value, ?string $region = '', array $refs = [])
	{
		return Lib::social()->type_tel_real($fb, $value, $region, $refs);
	}
}
